/** Bound all Supabase fetches, including auth and Storage, without retrying mutations. */
export async function boundedFetch(input:RequestInfo|URL,init?:RequestInit):Promise<Response> {
 const controller=new AbortController();
 const upstream=init?.signal||(input instanceof Request?input.signal:null);
 const abort=()=>controller.abort(upstream?.reason);
 if(upstream?.aborted)abort();else upstream?.addEventListener('abort',abort,{once:true});
 const upload=String(input).includes('/storage/v1/');
 const timer=setTimeout(()=>controller.abort(new DOMException('انتهت مهلة الاتصال. أعد المحاولة.','TimeoutError')),upload?120000:20000);
 try{return await fetch(input,{...init,signal:controller.signal});}
 finally{clearTimeout(timer);upstream?.removeEventListener('abort',abort);}
}
export function friendlyError(error:unknown):string {
 const message=error&&typeof error==='object'&&'message' in error?String(error.message):String(error);
 const known:Record<string,string>={invalid_transition:'تغيرت حالة العملية أو سبق تنفيذها. حدّث القائمة قبل المحاولة.',support_not_approved:'يجب اعتماد المساعدة قبل تنفيذ الصرف.',support_amount_required:'أدخل مبلغًا موجبًا للدعم النقدي.',insufficient_stock:'الرصيد المتاح في المستودع لا يكفي للكمية المطلوبة.',in_kind_valuation_required:'أدخل قيمة الدعم العيني قبل الصرف.',rejection_reason_required:'اكتب سبب الرفض ليظهر للمستفيد.',invalid_email:'أدخل بريدًا إلكترونيًا صحيحًا مثل name@example.com.',invalid_role:'الدور المختار غير متاح للدعوة. اختر دورًا آخر.',user_already_member:'هذا البريد مرتبط بعضو في الجمعية بالفعل. عدّل صلاحياته من قائمة الأعضاء.',invitation_unavailable:'الدعوة غير متاحة أو سبق قبولها أو إلغاؤها. حدّث قائمة الدعوات.',permission_denied:'لا تملك صلاحية تنفيذ هذا الإجراء.',role_name_required:'أدخل اسم الدور.',system_role_read_only:'أدوار النظام للعرض فقط. أنشئ دورًا مخصصًا لجمعيتك لتعديل صلاحياته.',cannot_change_own_role:'لا يمكنك تغيير دور حسابك بنفسك.',cannot_change_own_permissions:'لا يمكنك تعديل صلاحيات حسابك بنفسك.',only_owner_can_assign_owner:'نقل صلاحية المالك متاح لمالك الجمعية فقط.',cannot_remove_last_owner:'يجب بقاء مالك نشط واحد على الأقل للجمعية.',member_not_found:'الموظف غير متاح في جمعيتك.',role_not_found:'الدور غير متاح في جمعيتك.',invalid_beneficiary_name:'أدخل اسمًا بين حرفين و١٦٠ حرفًا.',invalid_beneficiary_phone:'أدخل رقم جوال صحيحًا من ٨ إلى ١٥ رقمًا.',beneficiary_request_conflict:'تعارضت محاولة الإنشاء مع سجل سابق. افتح الملف السابق أو ابدأ إضافة جديدة.',beneficiary_not_found:'الملف غير متاح في جمعيتك أو لا تملك صلاحية الوصول إليه.',invalid_account_code:'استخدم كودًا من ٢ إلى ٢٠ حرفًا لاتينيًا أو رقمًا أو نقطة أو شرطة.',invalid_account_name:'أدخل اسم حساب صحيحًا لا يتجاوز ٢٠٠ حرف.',account_identity_locked:'لا يمكن تغيير كود الحساب أو تصنيفه بعد إنشائه.',accounting_period_closed:'الفترة المالية مقفلة. اختر فترة مفتوحة أو أعد فتحها بصلاحية مناسبة.',journal_not_balanced:'إجمالي المدين لا يساوي إجمالي الدائن.',already_reversed:'تم عكس هذا القيد بالفعل.',account_not_found:'الحساب غير متاح أو غير نشط في جمعيتك.',invalid_journal_line:'راجع بنود القيد: مبلغ موجب في طرف واحد لكل بند.',period_not_found:'الفترة المالية غير متاحة.',budget_not_found_or_not_draft:'الموازنة غير متاحة أو سبق اعتمادها.',posted_entry_immutable:'لا يمكن تعديل قيد مرحّل. استخدم العكس لتصحيحه.',charity_code_mismatch:'كود الجمعية لا يطابق الدعوة.',invitation_email_mismatch_or_unconfirmed:'استخدم بريد الدعوة وفعّل البريد الإلكتروني أولًا.',account_already_linked:'هذا الحساب مرتبط بجمعية بالفعل. تواصل مع إدارة المنصة.',platform_account_cannot_join_charity:'حساب إدارة المنصة مستقل ولا يمكن ضمه لجمعية.',invitation_expired_or_invalid:'الدعوة منتهية أو مستخدمة أو أُلغيت. اطلب دعوة جديدة.',charity_unavailable:'الجمعية غير مفعلة حاليًا.',forbidden:'لا تملك صلاحية تنفيذ هذا الإجراء.',active_invitation_exists:'توجد دعوة سارية لهذا البريد. يمكنك إلغاء السابقة أولًا.'};
 return (/duplicate key.*accounting_accounts/i.test(message)?'كود الحساب مستخدم بالفعل. اختر كودًا مختلفًا.':known[message])||(/fetch|abort|timeout|network/i.test(message)?'تعذر الاتصال بالخدمة. تحقق من الإنترنت وأعد المحاولة.':message);
}
