begin;
do $$
declare owner_id uuid; c uuid; test_role uuid; staff uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); email text; inv jsonb; test_code text; result jsonb; content_id uuid; c2 uuid; second_code text; admin_id uuid; foreign_content uuid; second_token text;
begin
 select m.user_id,m.charity_id into owner_id,c from public.charity_members m join public.roles r on r.id=m.role_id join public.charities ch on ch.id=m.charity_id join public.charity_subscriptions s on s.charity_id=ch.id where m.status='active' and r.code='owner' and ch.status='approved' and s.status in('trial','active') and s.starts_at<=now() and (s.ends_at is null or s.ends_at>now()) limit 1;
 if c is null then raise exception 'No active owner test fixture'; end if;
 insert into public.charities(name_ar,slug,status) values('Rollback charity','smoke-'||gen_random_uuid()::text,'pending') returning id,charity_code into c2,second_code;
 insert into public.charity_public_content(charity_id,kind,title) values(c2,'impact','Foreign rollback content') returning id into foreign_content;
 if second_code is null or second_code=(select charity_code from public.charities where id=c) then raise exception 'new code failed'; end if;
 select id into test_role from public.roles where code='case_manager' and charity_id is null limit 1;
 if test_role is null then raise exception 'No test role'; end if;
 email:='smoke-'||staff::text||'@example.invalid';
 insert into auth.users(id,aud,role,email,email_confirmed_at,raw_user_meta_data,raw_app_meta_data,created_at,updated_at) values(staff,'authenticated','authenticated',email,now(),'{}','{}',now(),now()),(outsider,'authenticated','authenticated','smoke-'||outsider::text||'@example.invalid',now(),'{}','{}',now(),now());
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 select charity_code into test_code from public.charities where id=c;
 if test_code is null or (select count(*) from public.charities where charity_code=test_code)<>1 then raise exception 'code uniqueness failed'; end if;
 inv:=public.create_team_invitation(email,test_role);
 if inv->>'token' is null then raise exception 'invitation creation failed'; end if;
 if not exists(select 1 from public.member_invitations where id=(inv->>'invitation_id')::uuid) then raise exception 'wrong invitation table'; end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.accept_staff_invitation(inv->>'token',test_code); raise exception 'TEST: mismatched email accepted'; exception when others then if sqlerrm<>'invitation_email_mismatch_or_unconfirmed' then raise; end if; end;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 begin perform public.accept_staff_invitation(inv->>'token','JM-WRONG'); raise exception 'TEST: wrong code accepted'; exception when others then if sqlerrm<>'charity_code_mismatch' then raise; end if; end;
 result:=public.accept_staff_invitation(inv->>'token',test_code);
 if result->>'charity_id'<>c::text or not exists(select 1 from public.charity_members where user_id=staff and charity_id=c and role_id=test_role and status='active') then raise exception 'staff membership mismatch'; end if;
 begin perform public.accept_staff_invitation(inv->>'token',test_code); raise exception 'TEST: token reused'; exception when others then if sqlerrm<>'invitation_expired_or_invalid' then raise; end if; end;
 second_token:=encode(extensions.gen_random_bytes(32),'hex');
 insert into public.member_invitations(charity_id,email,role_id,token_hash,invited_by) values(c2,email,test_role,encode(extensions.digest(second_token,'sha256'),'hex'),owner_id);
 begin perform public.accept_staff_invitation(second_token,second_code); raise exception 'TEST: joined another charity'; exception when others then if sqlerrm<>'account_already_linked' then raise; end if; end;
 begin perform public.manage_public_content(); raise exception 'TEST: staff edited public site'; exception when others then if sqlerrm<>'forbidden' then raise; end if; end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 begin perform public.manage_public_content(jsonb_build_object('id',foreign_content,'kind','impact','title','Forbidden change')); raise exception 'TEST: foreign content modified'; exception when others then if sqlerrm<>'content_not_found' then raise; end if; end;
 result:=public.manage_public_content(jsonb_build_object('kind','campaign','title','Smoke draft','body','Rollback only','published',false,'donation_type','in_kind'));
 select id into content_id from public.charity_public_content where charity_id=c and title='Smoke draft';
 result:=public.manage_charity_public_site(jsonb_build_object('published',true));
 result:=public.public_charity_site(c);
 if exists(select 1 from jsonb_array_elements(result->'content') x where x->>'id'=content_id::text) then raise exception 'draft leaked'; end if;
 perform public.manage_public_content(jsonb_build_object('id',content_id,'kind','campaign','title','Smoke published','body','Rollback only','published',true,'donation_type','in_kind'));
 result:=public.public_charity_site(c);
 if not exists(select 1 from jsonb_array_elements(result->'content') x where x->>'id'=content_id::text) then raise exception 'published missing'; end if;
 if public.public_charity_site(c2) is not null then raise exception 'pending charity exposed'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 inv:=public.create_team_invitation('smoke-'||outsider::text||'@example.invalid',test_role);
 perform public.revoke_staff_invitation((inv->>'invitation_id')::uuid);
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.accept_staff_invitation(inv->>'token',test_code); raise exception 'TEST: revoked accepted'; exception when others then if sqlerrm<>'invitation_expired_or_invalid' then raise; end if; end;
 begin perform public.platform_workspace_directory(); raise exception 'TEST: outsider read platform'; exception when others then if sqlerrm<>'forbidden' then raise; end if; end;
 select user_id into admin_id from public.platform_admins where status='active' limit 1;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 if not exists(select 1 from jsonb_array_elements(public.platform_workspace_directory()) x where x->>'charity_code'=second_code) then raise exception 'platform cannot see code'; end if;
 if result ? 'members' or result ? 'donors' then raise exception 'private collections exposed'; end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.team_center(); raise exception 'TEST: outsider read team'; exception when others then if sqlerrm<>'forbidden' then raise; end if; end;
 if has_table_privilege('anon','public.charity_public_content','SELECT') or has_table_privilege('authenticated','public.charity_public_content','INSERT') then raise exception 'direct content grants exposed'; end if;
end $$;
rollback;
