import { useEffect,useState } from 'react';
import { BookOpen, RefreshCw, Search, TrendingDown, TrendingUp } from 'lucide-react';
import { supabase } from '../supabase';
import { getAccessState } from '../lib/rbac';

export default function Accounting(){
 const [rows,setRows]=useState<any[]>([]); const [accounts,setAccounts]=useState<any[]>([]); const [q,setQ]=useState(''); const [busy,setBusy]=useState(true); const [error,setError]=useState('');
 async function load(){setBusy(true);setError('');const a=await getAccessState();if(!a.charityId){setRows([]);setBusy(false);return;}const [j,ac]=await Promise.all([supabase.from('journal_entries').select('id,reference_type,reference_id,description,status,created_at,journal_lines(id,debit,credit,description,account_id,accounting_accounts(code,name_ar))').eq('charity_id',a.charityId).order('created_at',{ascending:false}).limit(100),supabase.from('accounting_accounts').select('id,code,name_ar,name_en,account_type,is_active').eq('charity_id',a.charityId).order('code')]);if(j.error) setError(j.error.message); else setRows(j.data||[]);setAccounts(ac.data||[]);setBusy(false)}
 useEffect(()=>{load()},[]);
 const filtered=rows.filter(x=>`${x.description||''} ${x.reference_type||''}`.toLowerCase().includes(q.toLowerCase()));
 const debit=filtered.reduce((s,x)=>s+(x.journal_lines||[]).reduce((z,l)=>z+Number(l.debit||0),0),0); const credit=filtered.reduce((s,x)=>s+(x.journal_lines||[]).reduce((z,l)=>z+Number(l.credit||0),0),0);
 return <main className="page"><div className="page-head"><div><div className="eyebrow">المحاسبة المالية</div><h1>دفتر القيود</h1><p>سجل محاسبي للقيود المرحلة الناتجة عن العمليات التشغيلية.</p></div><button className="secondary" onClick={load}><RefreshCw/> تحديث</button></div>
 <div className="kpis"><div className="kpi"><div className="kpi-icon"><TrendingUp/></div><span>إجمالي المدين</span><strong>{debit.toLocaleString('ar-SA')} ر.س</strong><small>آخر 100 قيد</small></div><div className="kpi"><div className="kpi-icon"><TrendingDown/></div><span>إجمالي الدائن</span><strong>{credit.toLocaleString('ar-SA')} ر.س</strong><small>آخر 100 قيد</small></div><div className="kpi"><div className="kpi-icon"><BookOpen/></div><span>الحسابات</span><strong>{accounts.length}</strong><small>حسابات الجمعية</small></div></div>
 <section className="panel"><div className="toolbar"><div className="search"><Search/><input placeholder="ابحث في وصف القيد أو المرجع" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{error&&<div className="error">{error}</div>}{busy?<div className="empty">جاري تحميل دفتر القيود...</div>:filtered.length?<div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الوصف</th><th>المرجع</th><th>الحالة</th><th>المدين</th><th>الدائن</th></tr></thead><tbody>{filtered.map(x=>{const d=(x.journal_lines||[]).reduce((s:any,l:any)=>s+Number(l.debit||0),0);const c=(x.journal_lines||[]).reduce((s:any,l:any)=>s+Number(l.credit||0),0);return <tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString('ar-SA')}</td><td><b>{x.description||'قيد محاسبي'}</b></td><td>{x.reference_type||'—'}</td><td><span className="badge success">{x.status==='posted'?'مرحّل':x.status}</span></td><td>{d.toLocaleString('ar-SA')} ر.س</td><td>{c.toLocaleString('ar-SA')} ر.س</td></tr>})}</tbody></table></div>:<div className="empty">لا توجد قيود محاسبية بعد. ستظهر هنا تلقائياً عند ترحيل التبرعات والعمليات المالية.</div>}</section></main>;
}