import { useEffect,useMemo,useState } from 'react';
import { BarChart3,Landmark,Plus,RefreshCw,RotateCcw,Scale,Search,WalletCards } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabase';
import { getAccessState } from '../lib/rbac';
import AccountingVouchers from '../components/AccountingVouchers';

const money=(v:any)=>Number(v||0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})+' ر.س';
const tabs=[['','نظرة عامة'],['vouchers','السندات'],['receipts','سندات القبض'],['payments','سندات الصرف'],['expenses','المصروفات'],['purchases','المشتريات'],['accounts','دليل الحسابات'],['journals','القيود اليومية'],['periods','الفترات المالية'],['cost-centers','مراكز التكلفة'],['funds','الصناديق'],['budgets','الموازنات'],['reports','القوائم والتقارير']];
export default function Accounting(){
 const n=useNavigate();const tab=window.location.pathname.split('/')[2]||'';const[accounts,setAccounts]=useState<any[]>([]),[journals,setJournals]=useState<any[]>([]),[periods,setPeriods]=useState<any[]>([]),[dimensions,setDimensions]=useState<any>({funds:[],cost_centers:[]}),[budgets,setBudgets]=useState<any[]>([]),[trial,setTrial]=useState<any[]>([]),[income,setIncome]=useState<any>({}),[balance,setBalance]=useState<any>({}),[fundReport,setFundReport]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const access=await getAccessState();if(!access.charityId){setLoading(false);return}const[a,j,p,d,b,t,i,bs,f]=await Promise.all([
  supabase.from('accounting_accounts').select('id,code,name_ar,name_en,account_type,is_active,parent_id').eq('charity_id',access.charityId).order('code'),
  supabase.from('journal_entries').select('id,entry_date,reference_type,description,status,created_at,reversal_of_id,journal_lines(id,debit,credit,description,account_id,accounting_accounts(code,name_ar))').eq('charity_id',access.charityId).order('entry_date',{ascending:false}).limit(200),
  supabase.rpc('accounting_periods'),supabase.rpc('accounting_dimensions'),supabase.rpc('accounting_budgets'),supabase.rpc('accounting_trial_balance'),supabase.rpc('accounting_income_statement'),supabase.rpc('accounting_balance_sheet'),supabase.rpc('accounting_fund_report')
 ]);const failed=a.error||j.error||p.error||d.error||b.error||t.error||i.error||bs.error||f.error;if(failed)setError(failed.message);else{setAccounts(a.data||[]);setJournals(j.data||[]);setPeriods((p.data||[])as any[]);setDimensions(d.data||{funds:[],cost_centers:[]});setBudgets((b.data||[])as any[]);setTrial(t.data||[]);setIncome(i.data||{});setBalance(bs.data||{});setFundReport((f.data||[])as any[])}setLoading(false)}
 useEffect(()=>{void load()},[tab]);
 const filtered=useMemo(()=>journals.filter(x=>`${x.description||''} ${x.reference_type||''}`.toLowerCase().includes(q.toLowerCase())),[journals,q]);
 async function initialize(){const r=await supabase.rpc('accounting_initialize');if(r.error)setError(r.error.message);else await load()}
 async function createPeriod(){const name=prompt('اسم الفترة المالية:')?.trim(),start=prompt('تاريخ البداية YYYY-MM-DD:')?.trim(),end=prompt('تاريخ النهاية YYYY-MM-DD:')?.trim();if(!name||!start||!end)return;const r=await supabase.rpc('accounting_create_period',{p_name:name,p_starts_on:start,p_ends_on:end});if(r.error)setError(r.error.message);else load()}
 async function closePeriod(id:string){if(!confirm('بعد الإقفال لن يُسمح بالترحيل داخل الفترة. هل تريد المتابعة؟'))return;const r=await supabase.rpc('accounting_close_period',{p_period_id:id});if(r.error)setError(r.error.message);else load()}
 async function createDimension(kind:'cost_center'|'fund'){const code=prompt('الكود:')?.trim(),name=prompt('الاسم بالعربية:')?.trim();if(!code||!name)return;const restriction=kind==='fund'&&confirm('هل الصندوق مقيد؟')?'restricted':'unrestricted';const r=await supabase.rpc('accounting_create_dimension',{p_kind:kind,p_code:code,p_name_ar:name,p_name_en:null,p_restriction_type:restriction});if(r.error)setError(r.error.message);else load()}
 async function reverse(id:string){const reason=prompt('سبب عكس القيد:')?.trim();if(!reason)return;const r=await supabase.rpc('accounting_reverse_journal',{p_entry_id:id,p_reason:reason});if(r.error)setError(r.error.message);else load()}
 const debit=trial.reduce((s,x)=>s+Number(x.debit||0),0),credit=trial.reduce((s,x)=>s+Number(x.credit||0),0);
 return <main className="module-page accounting-center"><div className="module-head"><div><span className="eyebrow"><Landmark/> النظام المالي</span><h1>مركز المحاسبة</h1><p>محاسبة القيد المزدوج، الفترات، الأبعاد، الموازنات والقوائم المالية.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div><nav className="module-tabs">{tabs.map(([path,label])=><button className={tab===path?'active':''}key={path}onClick={()=>n('/accounting'+(path?'/'+path:''))}>{label}</button>)}</nav>{error&&<div className="error">{error}</div>}{loading?<div className="loading">جاري تحميل المركز المالي...</div>:<>
 {tab===''&&<><div className="kpis"><K i={<Scale/>}t="إجمالي المدين"v={money(debit)}/><K i={<Scale/>}t="إجمالي الدائن"v={money(credit)}/><K i={<WalletCards/>}t="الإيرادات"v={money(income.revenue)}/><K i={<BarChart3/>}t="الفائض / العجز"v={money(income.surplus)}/></div><div className="report-grid"><section className="panel"><h2>المركز المالي</h2><Rows data={{'الأصول':money(balance.assets),'الالتزامات':money(balance.liabilities),'صافي الأصول':money(balance.net_assets),'القائمة متوازنة':balance.balanced?'نعم':'لا'}}/></section><section className="panel"><h2>جاهزية المحاسبة</h2><p>هيئ دليل الحسابات والفترة الافتراضية ومركز التكلفة والصندوق الأساسي بطريقة آمنة ومتكررة.</p><button className="primary"onClick={initialize}>تهيئة المحاسبة</button></section></div></>}
 {['vouchers','receipts','payments','expenses','purchases'].includes(tab)&&<AccountingVouchers type={({receipts:'receipt',payments:'payment',expenses:'expense',purchases:'purchase'} as Record<string,string>)[tab]} accounts={accounts} onChanged={load}/>}
 {tab==='accounts'&&<Table headers={['الكود','الحساب','النوع','الحالة']}rows={accounts.map(x=>[x.code,x.name_ar,x.account_type,x.is_active?'نشط':'موقوف'])}/>}
 {tab==='journals'&&<section className="data-card"><div className="module-toolbar"><div className="search-box"><Search/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="بحث في القيود..."/></div></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الوصف</th><th>المرجع</th><th>مدين</th><th>دائن</th><th/></tr></thead><tbody>{filtered.map(x=>{const d=(x.journal_lines||[]).reduce((s:number,l:any)=>s+Number(l.debit||0),0),c=(x.journal_lines||[]).reduce((s:number,l:any)=>s+Number(l.credit||0),0);return <tr key={x.id}><td>{new Date(x.entry_date||x.created_at).toLocaleDateString('ar-SA')}</td><td>{x.description}</td><td>{x.reference_type||'يدوي'}</td><td>{money(d)}</td><td>{money(c)}</td><td>{!x.reversal_of_id&&<button className="icon"onClick={()=>reverse(x.id)}title="عكس القيد"><RotateCcw/></button>}</td></tr>})}</tbody></table></div></section>}
 {tab==='periods'&&<section className="data-card"><div className="data-card-head"><strong>الفترات المالية</strong><button className="primary small"onClick={createPeriod}><Plus/> فترة جديدة</button></div><Table headers={['الفترة','البداية','النهاية','الحالة','']}rows={periods.map(x=>[x.name,new Date(x.starts_on).toLocaleDateString('ar-SA'),new Date(x.ends_on).toLocaleDateString('ar-SA'),x.status,x.status!=='closed'?<button className="secondary"onClick={()=>closePeriod(x.id)}>إقفال</button>:'مقفلة'])}/></section>}
 {tab==='cost-centers'&&<Dimension title="مراكز التكلفة"items={dimensions.cost_centers||[]}onCreate={()=>createDimension('cost_center')}/>}
 {tab==='funds'&&<Dimension title="الصناديق والأموال"items={dimensions.funds||[]}onCreate={()=>createDimension('fund')}fund/>}
 {tab==='budgets'&&<section className="data-card"><div className="data-card-head"><strong>الموازنات</strong><span>{budgets.length} موازنة</span></div>{!budgets.length?<div className="empty">لا توجد موازنات بعد. أنشئ فترة مالية أولًا ثم أضف الموازنة.</div>:<Table headers={['الموازنة','الفترة','الحالة','الإجمالي']}rows={budgets.map(x=>[x.name,x.period_name,x.status,money(x.total_amount)])}/>}</section>}
 {tab==='reports'&&<div className="report-grid"><section className="panel"><h2>ميزان المراجعة</h2><Table headers={['الكود','الحساب','مدين','دائن','الرصيد']}rows={trial.map(x=>[x.code,x.name_ar,money(x.debit),money(x.credit),money(x.balance)])}/></section><section className="panel"><h2>قائمة الدخل</h2><Rows data={{'الإيرادات':money(income.revenue),'المصروفات':money(income.expense),'الفائض / العجز':money(income.surplus)}}/></section><section className="panel"><h2>الميزانية العمومية</h2><Rows data={{'الأصول':money(balance.assets),'الالتزامات':money(balance.liabilities),'صافي الأصول':money(balance.net_assets),'فائض الفترة':money(balance.current_surplus)}}/></section><section className="panel"><h2>تقرير الأموال</h2>{fundReport.length?<Table headers={['الصندوق','الإيرادات','المصروفات','الرصيد']}rows={fundReport.map(x=>[x.name_ar||x.fund_name,money(x.revenue),money(x.expense),money(x.balance)])}/>:<div className="empty">لا توجد حركة على الصناديق.</div>}</section></div>}
 </>}</main>
}
function K({i,t,v}:{i:React.ReactNode;t:string;v:string}){return <div className="kpi"><div className="kpi-icon">{i}</div><span>{t}</span><strong>{v}</strong><small>حسب القيود المرحلة</small></div>}
function Rows({data}:{data:Record<string,any>}){return <div className="detail-list">{Object.entries(data).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Dimension({title,items,onCreate,fund=false}:{title:string;items:any[];onCreate:()=>void;fund?:boolean}){return <section className="data-card"><div className="data-card-head"><strong>{title}</strong><button className="primary small"onClick={onCreate}><Plus/> إضافة</button></div><Table headers={fund?['الكود','الاسم','نوع التقييد','الحالة']:['الكود','الاسم','الحالة']}rows={items.map(x=>fund?[x.code,x.name_ar,x.restriction_type==='restricted'?'مقيد':'غير مقيد',x.is_active?'نشط':'موقوف']:[x.code,x.name_ar,x.is_active?'نشط':'موقوف'])}/></section>}
