import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { BarChart3,Landmark,Plus,RefreshCw,RotateCcw,Scale,Search,WalletCards } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { supabase } from '../supabase';
import { getAccessState } from '../lib/rbac';
import AccountingVouchers from '../components/AccountingVouchers';
import AccountingPeriods from '../components/AccountingPeriods';
import { JournalComposer, BudgetWorkbench, AccountWorkbench } from '../components/AccountingWorkbench';
import { friendlyError } from '../lib/requests';

const money=(v:any)=>Number(v||0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})+' ر.س';
const tabs=[['','نظرة عامة'],['vouchers','السندات'],['receipts','سندات القبض'],['payments','سندات الصرف'],['expenses','المصروفات'],['purchases','المشتريات'],['accounts','دليل الحسابات'],['journals','القيود اليومية'],['periods','الفترات المالية'],['cost-centers','مراكز التكلفة'],['funds','الصناديق'],['budgets','الموازنات'],['reports','القوائم والتقارير']];
export default function Accounting(){
 const n=useNavigate();const location=useLocation();const tab=location.pathname.split('/')[2]||'';const request=useRef(0);const [canManage,setCanManage]=useState(false);const[accounts,setAccounts]=useState<any[]>([]),[journals,setJournals]=useState<any[]>([]),[periods,setPeriods]=useState<any[]>([]),[dimensions,setDimensions]=useState<any>({funds:[],cost_centers:[]}),[budgets,setBudgets]=useState<any[]>([]),[trial,setTrial]=useState<any[]>([]),[income,setIncome]=useState<any>({}),[balance,setBalance]=useState<any>({}),[fundReport,setFundReport]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{const id=++request.current;setLoading(true);setError('');
  try{const access=await getAccessState(true);if(!access.charityId||!access.workspaceEnabled)throw new Error('مساحة الجمعية غير متاحة. راجع حالة الاشتراك.');
   const tasks:Promise<void>[]=[];
   const apply=async(query:PromiseLike<any>,setter:(data:any)=>void,fallback:any)=>{const r=await query;if(r.error)throw r.error;if(id===request.current)setter(r.data??fallback)};
   const financial=tab===''||tab==='reports';
   if(['accounts','journals','budgets','vouchers','receipts','payments','expenses','purchases'].includes(tab))tasks.push(apply(supabase.from('accounting_accounts').select('id,code,name_ar,name_en,account_type,is_active,parent_id').eq('charity_id',access.charityId).order('code'),setAccounts,[]));
   if(tab==='journals')tasks.push(apply(supabase.from('journal_entries').select('id,entry_date,reference_type,description,status,created_at,reversal_of_id,journal_lines(id,debit,credit,description,account_id,accounting_accounts(code,name_ar))').eq('charity_id',access.charityId).order('entry_date',{ascending:false}).order('id').limit(200),setJournals,[]));
   if(['periods','journals','budgets'].includes(tab))tasks.push(apply(supabase.rpc('accounting_periods'),setPeriods,[]));
   if(['cost-centers','funds','journals','budgets'].includes(tab))tasks.push(apply(supabase.rpc('accounting_dimensions'),setDimensions,{funds:[],cost_centers:[]}));
   if(tab==='budgets')tasks.push(apply(supabase.rpc('accounting_budgets'),setBudgets,[]));
   if(financial){tasks.push(apply(supabase.rpc('accounting_trial_balance'),setTrial,[]),apply(supabase.rpc('accounting_income_statement'),setIncome,{}),apply(supabase.rpc('accounting_balance_sheet'),setBalance,{}));}
   if(tab==='reports')tasks.push(apply(supabase.rpc('accounting_fund_report'),setFundReport,[]));
   const results=await Promise.allSettled(tasks);const failed=results.find(r=>r.status==='rejected');if(failed?.status==='rejected')throw failed.reason;
   if(id===request.current)setCanManage(access.permissions.includes('accounting.manage'));
  }catch(e){if(id===request.current)setError(friendlyError(e));}finally{if(id===request.current)setLoading(false);}
 },[tab]);
 useEffect(()=>{void load();return()=>{request.current++}},[load]);
 const filtered=useMemo(()=>journals.filter(x=>`${x.description||''} ${x.reference_type||''}`.toLowerCase().includes(q.toLowerCase())),[journals,q]);
 async function initialize(){const r=await supabase.rpc('accounting_initialize');if(r.error)setError(friendlyError(r.error));else await load()}
 async function createDimension(kind:'cost_center'|'fund'){const code=prompt('الكود:')?.trim(),name=prompt('الاسم بالعربية:')?.trim();if(!code||!name)return;const restriction=kind==='fund'&&confirm('هل الصندوق مقيد؟')?'restricted':'unrestricted';const r=await supabase.rpc('accounting_create_dimension',{p_kind:kind,p_code:code,p_name_ar:name,p_name_en:null,p_restriction_type:restriction});if(r.error)setError(friendlyError(r.error));else load()}
 async function reverse(id:string){const reason=prompt('سبب عكس القيد:')?.trim();if(!reason)return;const r=await supabase.rpc('accounting_reverse_journal',{p_entry_id:id,p_reason:reason});if(r.error)setError(friendlyError(r.error));else load()}
 const debit=trial.reduce((s,x)=>s+Number(x.debit||0),0),credit=trial.reduce((s,x)=>s+Number(x.credit||0),0);
 return <main className="module-page accounting-center"><div className="module-head"><div><span className="eyebrow"><Landmark/> النظام المالي</span><h1>مركز المحاسبة</h1><p>محاسبة القيد المزدوج، الفترات، الأبعاد، الموازنات والقوائم المالية.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div><nav className="module-tabs">{tabs.map(([path,label])=><button className={tab===path?'active':''}key={path}onClick={()=>n('/accounting'+(path?'/'+path:''))}>{label}</button>)}</nav>{error&&<div className="error">{error}</div>}{loading?<div className="loading" role="status">جاري تحميل المركز المالي...</div>:error?<button className="secondary" onClick={load}>إعادة المحاولة</button>:<>
 {tab===''&&<><div className="kpis"><K i={<Scale/>}t="إجمالي المدين"v={money(debit)}/><K i={<Scale/>}t="إجمالي الدائن"v={money(credit)}/><K i={<WalletCards/>}t="الإيرادات"v={money(income.revenue)}/><K i={<BarChart3/>}t="الفائض / العجز"v={money(income.surplus)}/></div><div className="report-grid"><section className="panel"><h2>المركز المالي</h2><Rows data={{'الأصول':money(balance.assets),'الالتزامات':money(balance.liabilities),'صافي الأصول':money(balance.net_assets),'القائمة متوازنة':balance.balanced?'نعم':'لا'}}/></section><section className="panel"><h2>جاهزية المحاسبة</h2><p>هيئ دليل الحسابات والفترة الافتراضية ومركز التكلفة والصندوق الأساسي بطريقة آمنة ومتكررة.</p><button className="primary" disabled={!canManage} onClick={initialize}>تهيئة المحاسبة</button></section></div></>}
 {['vouchers','receipts','payments','expenses','purchases'].includes(tab)&&<AccountingVouchers type={({receipts:'receipt',payments:'payment',expenses:'expense',purchases:'purchase'} as Record<string,string>)[tab]} accounts={accounts} canManage={canManage} onChanged={load}/>}
 {tab==='accounts'&&<AccountWorkbench accounts={accounts} canManage={canManage} onChanged={load}/>}
 {tab==='journals'&&<><JournalComposer accounts={accounts} dimensions={dimensions} periods={periods} canManage={canManage} onChanged={load}/><p className="muted">عرض أحدث ٢٠٠ قيد. البحث داخل القيود المعروضة.</p><section className="data-card"><div className="module-toolbar"><div className="search-box"><Search/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="بحث في القيود..."/></div></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الوصف</th><th>المرجع</th><th>مدين</th><th>دائن</th><th/></tr></thead><tbody>{filtered.map(x=>{const d=(x.journal_lines||[]).reduce((s:number,l:any)=>s+Number(l.debit||0),0),c=(x.journal_lines||[]).reduce((s:number,l:any)=>s+Number(l.credit||0),0);return <tr key={x.id}><td>{new Date(x.entry_date||x.created_at).toLocaleDateString('ar-SA')}</td><td>{x.description}</td><td>{x.reference_type||'يدوي'}</td><td>{money(d)}</td><td>{money(c)}</td><td>{canManage&&!x.reversal_of_id&&<button className="icon"onClick={()=>reverse(x.id)}title="عكس القيد"><RotateCcw/></button>}</td></tr>})}</tbody></table></div></section></>}
 {tab==='periods'&&<AccountingPeriods periods={periods} canManage={canManage} onChanged={load}/>}
 {tab==='cost-centers'&&<Dimension title="مراكز التكلفة"items={dimensions.cost_centers||[]}canManage={canManage} onCreate={()=>createDimension('cost_center')}/>}
 {tab==='funds'&&<Dimension title="الصناديق والأموال"items={dimensions.funds||[]}canManage={canManage} onCreate={()=>createDimension('fund')}fund/>}
 {tab==='budgets'&&<BudgetWorkbench accounts={accounts} dimensions={dimensions} periods={periods} budgets={budgets} canManage={canManage} onChanged={load}/>}
 {tab==='reports'&&<div className="report-grid"><section className="panel"><h2>ميزان المراجعة</h2><Table headers={['الكود','الحساب','مدين','دائن','الرصيد']}rows={trial.map(x=>[x.code,x.name_ar,money(x.debit),money(x.credit),money(x.balance)])}/></section><section className="panel"><h2>قائمة الدخل</h2><Rows data={{'الإيرادات':money(income.revenue),'المصروفات':money(income.expense),'الفائض / العجز':money(income.surplus)}}/></section><section className="panel"><h2>الميزانية العمومية</h2><Rows data={{'الأصول':money(balance.assets),'الالتزامات':money(balance.liabilities),'صافي الأصول':money(balance.net_assets),'فائض الفترة':money(balance.current_surplus)}}/></section><section className="panel"><h2>تقرير الأموال</h2>{fundReport.length?<Table headers={['الصندوق','الإيرادات','المصروفات','الرصيد']}rows={fundReport.map(x=>[x.name_ar||x.fund_name,money(x.revenue),money(x.expense),money(x.balance)])}/>:<div className="empty">لا توجد حركة على الصناديق.</div>}</section></div>}
 </>}</main>
}
function K({i,t,v}:{i:React.ReactNode;t:string;v:string}){return <div className="kpi"><div className="kpi-icon">{i}</div><span>{t}</span><strong>{v}</strong><small>حسب القيود المرحلة</small></div>}
function Rows({data}:{data:Record<string,any>}){return <div className="detail-list">{Object.entries(data).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Dimension({title,items,onCreate,fund=false,canManage}:{title:string;items:any[];onCreate:()=>void;fund?:boolean;canManage:boolean}){return <section className="data-card"><div className="data-card-head"><strong>{title}</strong><button className="primary small" disabled={!canManage} onClick={onCreate}><Plus/> إضافة</button></div><Table headers={fund?['الكود','الاسم','نوع التقييد','الحالة']:['الكود','الاسم','الحالة']}rows={items.map(x=>fund?[x.code,x.name_ar,x.restriction_type==='restricted'?'مقيد':'غير مقيد',x.is_active?'نشط':'موقوف']:[x.code,x.name_ar,x.is_active?'نشط':'موقوف'])}/></section>}
