import { useEffect,useState } from 'react';
import { CheckCircle2,Clock3,RefreshCw,ShieldCheck,XCircle } from 'lucide-react';
import { supabase } from '../supabase';

export default function Approvals(){
 const[data,setData]=useState<any>({items:[],pending:0}),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){const r=await supabase.rpc('approval_inbox');if(r.error)setError(r.error.message);else setData(r.data||{items:[],pending:0})}useEffect(()=>{void load()},[]);
 async function act(id:string,decision:'approved'|'rejected'){const note=window.prompt(decision==='approved'?'ملاحظة الاعتماد (اختياري):':'سبب الرفض:')?.trim()||null;if(decision==='rejected'&&!note)return;setBusy(id);const r=await supabase.rpc('act_on_approval',{p_request_id:id,p_decision:decision,p_note:note});if(r.error)setError(r.error.message);else await load();setBusy('')}
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><ShieldCheck/> محرك الموافقات</span><h1>صندوق الموافقات</h1><p>الطلبات الحساسة مرتبة حسب الخطوة الحالية والصلاحية المطلوبة.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div>{error&&<div className="error">{error}</div>}<div className="kpis"><div className="kpi"><div className="kpi-icon"><Clock3/></div><span>بانتظار قرارك</span><strong>{Number(data.pending||0).toLocaleString('ar-SA')}</strong><small>حسب صلاحيات حسابك</small></div></div>{!(data.items||[]).length?<section className="data-card empty"><CheckCircle2 size={42}/><h2>لا توجد موافقات معلقة</h2><p>ستظهر هنا العمليات التي وصلت إلى خطوتك.</p></section>:<section className="approval-grid">{data.items.map((x:any)=><article className="approval-card"key={x.id||x.request_id}><div className="approval-head"><span>{x.operation_type||x.entity_type||'طلب اعتماد'}</span><b>{Number(x.amount||0).toLocaleString('ar-SA')} ر.س</b></div><h3>{x.title_ar||x.description||'عملية بانتظار الاعتماد'}</h3><p>الخطوة الحالية: {x.current_step_name||x.step_name||x.current_step||'المراجعة'}</p><div className="approval-timeline"><span className="done">تم الطلب</span><span className="current">الاعتماد الحالي</span><span>التنفيذ</span></div><div className="action-row"><button className="primary small"disabled={!!busy}onClick={()=>act(x.id||x.request_id,'approved')}><CheckCircle2/> اعتماد</button><button className="danger-button"disabled={!!busy}onClick={()=>act(x.id||x.request_id,'rejected')}><XCircle/> رفض</button></div></article>)}</section>}</main>
}
