import { useEffect,useState } from 'react';
import { HeartHandshake,LogIn,ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabase';
import './beneficiary.css';

export default function BeneficiaryLogin(){
 const n=useNavigate();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[invite,setInvite]=useState('');
 useEffect(()=>{const t=new URLSearchParams(window.location.search).get('invite')||localStorage.getItem('jamaity_beneficiary_invite')||'';if(t){localStorage.setItem('jamaity_beneficiary_invite',t);setInvite(t)}},[]);
 async function go(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await supabase.auth.signInWithPassword({email:email.trim(),password});if(r.error)throw r.error;const token=localStorage.getItem('jamaity_beneficiary_invite')||invite;if(token){const a=await supabase.rpc('accept_beneficiary_invitation',{p_token:token});if(a.error)throw a.error;localStorage.removeItem('jamaity_beneficiary_invite');n('/beneficiary',{replace:true});return}const app=await supabase.rpc('my_beneficiary_application');if(app.error)throw app.error;const data=app.data as any;if(data?.beneficiary_id)n('/beneficiary',{replace:true});else if(data?.id)n('/beneficiary/documents',{replace:true});else n('/beneficiary-apply',{replace:true})}catch(x:any){setError(x.message||'تعذر تسجيل الدخول')}finally{setBusy(false)}}
 return <main className="auth beneficiary-auth"><div className="auth-card"><div className="auth-icon"><HeartHandshake/></div><h1>دخول المستفيد</h1><p>تابع طلب الانضمام وطلبات الدعم والإشعارات من حساب واحد.</p><div className="success"><ShieldCheck/> حسابات المستفيدين منفصلة عن حسابات موظفي الجمعيات.</div><form onSubmit={go}><label>البريد الإلكتروني<input type="email"required autoComplete="email"value={email}onChange={e=>setEmail(e.target.value)}/></label><label>كلمة المرور<input type="password"required autoComplete="current-password"value={password}onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary wide"disabled={busy}><LogIn size={18}/>{busy?'جاري الدخول...':'دخول إلى بوابتي'}</button></form><button className="link"onClick={()=>n('/forgot-password?portal=beneficiary')}>نسيت كلمة المرور؟</button><button className="link"onClick={()=>n(invite?'/beneficiary-register?invite='+encodeURIComponent(invite):'/beneficiary-register')}>إنشاء حساب مستفيد</button></div></main>
}
