import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2,Clock3,RefreshCw,Search,UserCheck,XCircle } from 'lucide-react';
import { supabase } from '../supabase';

export default function BeneficiaryApplications(){
 const[rows,setRows]=useState<any[]>([]),[filter,setFilter]=useState('submitted'),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const r=await supabase.rpc('charity_beneficiary_applications',{p_status:filter==='all'?null:filter});if(r.error)setError(r.error.message);else setRows((r.data||[])as any[]);setLoading(false)}
 useEffect(()=>{void load()},[filter]);
 const shown=useMemo(()=>rows.filter(x=>`${x.full_name} ${x.phone||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function review(id:string,decision:'under_review'|'approved'|'rejected'){let reason:string|null=null;if(decision==='rejected'){reason=window.prompt('اكتب سبب الرفض الذي سيظهر للمستفيد:')?.trim()||null;if(!reason)return}setBusy(id+decision);setError('');const r=await supabase.rpc('review_beneficiary_application',{p_application_id:id,p_decision:decision,p_reason:reason});if(r.error)setError(r.error.message);else await load();setBusy('')}
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><UserCheck size={15}/> رحلة المستفيد</span><h1>طلبات انضمام المستفيدين</h1><p>راجع الطلبات، ثم اقبلها لإنشاء ملف المستفيد وربط حسابه تلقائيًا.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div>{error&&<div className="error">{error}</div>}<section className="data-card"><div className="module-toolbar"><div className="search-box"><Search/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="ابحث بالاسم أو الجوال..."/></div><select value={filter}onChange={e=>setFilter(e.target.value)}><option value="all">كل الطلبات</option><option value="submitted">جديدة</option><option value="under_review">تحت المراجعة</option><option value="approved">مقبولة</option><option value="rejected">مرفوضة</option></select></div>{loading?<div className="empty">جاري تحميل الطلبات...</div>:!shown.length?<div className="empty">لا توجد طلبات في هذه الحالة.</div>:<div className="application-list">{shown.map(x=><article className="application-row"key={x.id}><div><b>{x.full_name}</b><p>{x.phone||'لا يوجد جوال'} · {new Date(x.created_at).toLocaleDateString('ar-SA')}</p>{x.rejection_reason&&<small className="error-text">{x.rejection_reason}</small>}</div><span className="status inactive">{x.status==='submitted'?'جديد':x.status==='under_review'?'تحت المراجعة':x.status==='approved'?'مقبول':'مرفوض'}</span><div className="action-row">{x.status==='submitted'&&<button className="secondary"disabled={!!busy}onClick={()=>review(x.id,'under_review')}><Clock3/> بدء المراجعة</button>}{!['approved','withdrawn'].includes(x.status)&&<><button className="primary small"disabled={!!busy}onClick={()=>review(x.id,'approved')}><CheckCircle2/> قبول</button><button className="danger-button"disabled={!!busy}onClick={()=>review(x.id,'rejected')}><XCircle/> رفض</button></>}</div></article>)}</div>}</section></main>
}
