import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3, FileText, HeartHandshake, Plus, RefreshCw, ShieldCheck, UserRound, X } from 'lucide-react';
import { supabase } from '../supabase';

type Summary = { beneficiary: { id:string; full_name:string; phone:string|null; status:string; created_at:string }; cases:{id:string;case_number:string;title:string;status:string;priority:string;created_at:string;updated_at:string}[]; support:{id:string;support_type:string;amount:number|null;quantity:number|null;status:string;approval_status:string;provided_at:string|null;created_at:string;notes:string|null}[] };
type Request={id:string;support_type:string;title:string;description:string;requested_amount:number|null;requested_quantity:number|null;status:string;rejection_reason:string|null;created_at:string};
const caseLabel:any={open:'مفتوحة',in_progress:'قيد المعالجة',approved:'معتمدة',closed:'مغلقة',rejected:'مرفوضة',pending:'قيد المراجعة'};
const requestLabel:any={submitted:'تم الإرسال',under_review:'قيد المراجعة',approved:'تمت الموافقة',rejected:'مرفوض',fulfilled:'تم التنفيذ',cancelled:'ملغي'};
const supportLabel:any={cash:'دعم مالي',in_kind:'دعم عيني','عينى':'دعم عيني','in-kind':'دعم عيني'};
const fmtDate=(v:string|null)=>v?new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(v)):'—';

export default function BeneficiaryPortal(){
 const[data,setData]=useState<Summary|null>(null);const[requests,setRequests]=useState<Request[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');const[formOpen,setFormOpen]=useState(false);const[busy,setBusy]=useState(false);const[formError,setFormError]=useState('');const[f,setF]=useState({type:'financial',title:'',description:'',amount:'',quantity:''});
 async function load(){setRefreshing(true);setError('');const [s,r]=await Promise.all([supabase.rpc('beneficiary_portal_summary'),supabase.rpc('beneficiary_support_requests')]);if(s.error)setError(s.error.message);else setData(s.data as Summary);if(!r.error)setRequests((r.data||[])as Request[]);else if(!s.error)setError(r.error.message);setLoading(false);setRefreshing(false)}
 useEffect(()=>{load()},[]);
 const counts=useMemo(()=>({cases:data?.cases.length||0,support:data?.support.length||0,executed:data?.support.filter(x=>x.status==='executed').length||0}),[data]);
 async function submit(e:any){e.preventDefault();setBusy(true);setFormError('');try{if(!f.title.trim()||!f.description.trim())throw new Error('أكمل عنوان الطلب ووصف الاحتياج.');if(f.type==='financial'&&!f.amount)throw new Error('أدخل قيمة المساعدة المطلوبة.');const r=await supabase.rpc('create_beneficiary_support_request',{p_support_type:f.type,p_title:f.title.trim(),p_description:f.description.trim(),p_requested_amount:f.amount?Number(f.amount):null,p_requested_quantity:f.quantity?Number(f.quantity):null});if(r.error)throw r.error;setF({type:'financial',title:'',description:'',amount:'',quantity:''});setFormOpen(false);await load()}catch(x:any){setFormError(x.message||'تعذر إرسال الطلب')}finally{setBusy(false)}}
 if(loading)return <main className="module-page"><div className="loading">جاري تحميل ملفك بأمان…</div></main>;
 if(error)return <main className="module-page"><div className="data-card empty"><AlertCircle size={42}/><h2>تعذر فتح بوابة المستفيد</h2><p>{error}</p><button className="secondary" onClick={load}>إعادة المحاولة</button></div></main>;
 if(!data)return null;
 return <main className="module-page beneficiary-portal">
  <div className="module-head"><div><div className="eyebrow"><ShieldCheck size={16}/> بوابة المستفيد</div><h1>مرحباً، {data.beneficiary.full_name}</h1><p>تابع طلباتك وقرارات الدعم وسجل ما تم تقديمه لك من مكان واحد.</p></div><div className="hero-actions"><button className="secondary" onClick={load} disabled={refreshing}><RefreshCw size={17}/> تحديث</button><button className="primary" onClick={()=>setFormOpen(true)}><Plus size={18}/> طلب مساعدة جديد</button></div></div>
  {formOpen&&<section className="panel request-form-panel"><div className="panel-title"><div><span>طلب جديد</span><h2>بيانات الاحتياج</h2></div><button className="icon" onClick={()=>setFormOpen(false)}><X/></button></div><form onSubmit={submit}><label>نوع المساعدة<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="financial">مساعدة مالية</option><option value="in_kind">مساعدة عينية</option><option value="medical">مساعدة علاجية</option><option value="education">مساعدة تعليمية</option><option value="housing">مساعدة سكنية</option><option value="other">أخرى</option></select></label><label>عنوان الطلب<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="مثال: طلب مساعدة لتغطية مصاريف العلاج"/></label><label>شرح الاحتياج<textarea required rows={5} value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="اشرح الحالة والاحتياج بالتفصيل..."/></label><div className="request-two"><label>المبلغ المطلوب<input type="number" min="0.01" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})} placeholder="ر.س"/></label><label>الكمية المطلوبة<input type="number" min="0.001" step="0.001" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})} placeholder="اختياري"/></label></div>{formError&&<div className="error">{formError}</div>}<button className="primary wide" disabled={busy}>{busy?'جاري إرسال الطلب...':'إرسال طلب المساعدة'}</button></form></section>}
  <section className="profile-hero beneficiary-hero"><div className="profile-avatar"><UserRound size={32}/></div><div><h1>{data.beneficiary.full_name}</h1><p><span>{data.beneficiary.phone||'رقم الجوال غير معروض'}</span></p></div><span className="status-pill">{data.beneficiary.status==='active'?'حساب نشط':'الحساب موقوف'}</span></section>
  <div className="stat-strip"><div><b>{counts.cases}</b><span>الطلبات والحالات</span></div><div><b>{counts.support}</b><span>قرارات الدعم</span></div><div><b>{counts.executed}</b><span>دعم تم تنفيذه</span></div></div>
  <div className="profile-grid"><section className="panel"><div className="panel-title"><div><span>رحلة الطلب</span><h2>حالاتي</h2></div><FileText size={22}/></div>{data.cases.length===0?<div className="empty"><Clock3/><span>لا توجد حالات مسجلة حالياً.</span></div>:<div className="detail-list">{data.cases.map(c=><div key={c.id}><div><strong>{c.title}</strong><span>{c.case_number} · {fmtDate(c.updated_at)}</span></div><span className={`status ${c.status==='closed'||c.status==='approved'?'active':c.status==='rejected'?'blocked':'inactive'}`}>{caseLabel[c.status]||c.status}</span></div>)}</div>}</section><section className="panel"><div className="panel-title"><div><span>سجل الاستحقاق</span><h2>الدعم المقدم</h2></div><HeartHandshake size={22}/></div>{data.support.length===0?<div className="empty"><HeartHandshake/><span>لم يتم تسجيل دعم معتمد حتى الآن.</span></div>:<div>{data.support.map(s=><div className="list-row" key={s.id}><div className="row-icon"><CheckCircle2 size={20}/></div><div><strong>{supportLabel[s.support_type]||s.support_type}</strong><p>{s.amount!=null?`${Number(s.amount).toLocaleString('ar-SA')} ر.س`:s.quantity!=null?`الكمية: ${s.quantity}`:'دعم مسجل'} · {fmtDate(s.provided_at||s.created_at)}</p>{s.notes&&<p>{s.notes}</p>}</div><span className="status active">{s.status==='executed'?'تم التنفيذ':'معتمد'}</span></div>)}</div>}</section></div>
  <section className="panel"><div className="panel-title"><div><span>المتابعة</span><h2>طلبات المساعدة</h2></div><FileText size={22}/></div>{!requests.length?<div className="empty"><FileText/><span>لا توجد طلبات مساعدة مرسلة بعد.</span></div>:<div className="request-list">{requests.map(r=><article className="request-item" key={r.id}><div className="request-main"><div className="request-icon"><FileText size={20}/></div><div><h3>{r.title}</h3><p>{r.description}</p><small>{fmtDate(r.created_at)} · {r.support_type}</small>{r.rejection_reason&&<div className="request-reason">سبب الرفض: {r.rejection_reason}</div>}</div></div><div className="request-status"><span className={`status ${r.status==='rejected'||r.status==='cancelled'?'blocked':r.status==='approved'||r.status==='fulfilled'?'active':'inactive'}`}>{requestLabel[r.status]||r.status}</span>{r.requested_amount&&<b>{Number(r.requested_amount).toLocaleString('ar-SA')} ر.س</b>}</div></article>)}</div>}</section>
  <div className="privacy-note"><ShieldCheck size={22}/><div><strong>خصوصيتك أولاً</strong><p>لا نعرض رقم الهوية الوطنية داخل البوابة. الوصول إلى بياناتك مرتبط بحساب المستفيد الموثق من المنصة.</p></div></div>
 </main>;
}
