import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,Building2,CheckCircle2,Clock3,HeartHandshake,MapPin,Search,ShieldCheck,XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabase';
import './beneficiary.css';

type Charity={id:string;name_ar:string;description_ar?:string;city?:string;region?:string;logo_url?:string};
export default function BeneficiaryApply(){
 const n=useNavigate();const preset=new URLSearchParams(window.location.search).get('charity')||'';const[user,setUser]=useState<any>(undefined),[application,setApplication]=useState<any>(null),[rows,setRows]=useState<Charity[]>([]),[selected,setSelected]=useState(preset),[region,setRegion]=useState(''),[city,setCity]=useState(''),[q,setQ]=useState(''),[form,setForm]=useState({fullName:'',phone:'',nationalId:''}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function loadDirectory(){setLoading(true);const r=await supabase.rpc('approved_charities_directory',{p_region:region.trim()||null,p_city:city.trim()||null});if(r.error)setError(r.error.message);else setRows((r.data||[])as Charity[]);setLoading(false)}
 useEffect(()=>{(async()=>{const auth=await supabase.auth.getUser();setUser(auth.data.user||null);await loadDirectory();if(auth.data.user){const a=await supabase.rpc('my_beneficiary_application');if(!a.error&&a.data&&Object.keys(a.data as object).length)setApplication(a.data)}})()},[]);
 const shown=useMemo(()=>rows.filter(x=>`${x.name_ar} ${x.city||''} ${x.region||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return setError('اختر الجمعية أولًا.');setBusy(true);setError('');const r=await supabase.rpc('submit_beneficiary_application',{p_charity_id:selected,p_full_name:form.fullName.trim(),p_phone:form.phone.trim(),p_national_id:form.nationalId.trim()});if(r.error)setError(r.error.message);else{const a=await supabase.rpc('my_beneficiary_application');setApplication(a.data)}setBusy(false)}
 if(user===undefined)return <main className="module-page"><div className="loading">جاري التحقق من حساب المستفيد...</div></main>;
 if(!user)return <main className="auth"><div className="auth-card"><div className="auth-icon"><HeartHandshake/></div><h1>ابدأ طلب الانضمام</h1><p>سجّل الدخول أو أنشئ حساب مستفيد أولًا، ثم اختر الجمعية المناسبة في منطقتك.</p><button className="primary wide"onClick={()=>n('/beneficiary-register')}>إنشاء حساب مستفيد</button><button className="secondary wide"onClick={()=>n('/beneficiary-login')}>تسجيل الدخول</button></div></main>;
 if(application)return <ApplicationStatus application={application} onRetry={()=>setApplication(null)} onPortal={()=>n('/beneficiary')}/>;
 return <main className="module-page beneficiary-apply"><button className="back-link"onClick={()=>n('/directory')}><ArrowRight/> دليل الجمعيات</button><div className="module-head"><div><span className="eyebrow"><ShieldCheck size={15}/> طلب انضمام آمن</span><h1>ابحث عن جمعية في منطقتك</h1><p>تظهر هنا الجمعيات المعتمدة ذات الاشتراك الفعال فقط.</p></div></div>
 <div className="directory-toolbar directory-filters"><div className="search-box"><Search size={18}/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="اسم الجمعية"/></div><input value={region}onChange={e=>setRegion(e.target.value)}placeholder="المنطقة"/><input value={city}onChange={e=>setCity(e.target.value)}placeholder="المدينة"/><button className="primary small"onClick={loadDirectory}>بحث</button></div>
 {loading?<div className="empty">جاري تحميل الجمعيات...</div>:<section className="select-charities">{shown.map(x=><button type="button"className={'select-charity '+(selected===x.id?'selected':'')}key={x.id}onClick={()=>setSelected(x.id)}><span className="charity-logo"><Building2/></span><span><b>{x.name_ar}</b><small><MapPin size={13}/>{x.city||'السعودية'}{x.region&&` · ${x.region}`}</small><p>{x.description_ar||'جمعية معتمدة على منصة جمعيتي.'}</p></span>{selected===x.id&&<CheckCircle2/>}</button>)}</section>}
 <form className="data-card application-form"onSubmit={submit}><div className="data-card-head"><div><strong>بيانات طلب الانضمام</strong><p>يُحوّل رقم الهوية إلى بصمة مشفرة داخل قاعدة البيانات.</p></div></div><label>الاسم الكامل<input required minLength={3}value={form.fullName}onChange={e=>setForm({...form,fullName:e.target.value})}/></label><div className="form-grid"><label>رقم الجوال<input required inputMode="tel"value={form.phone}onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>رقم الهوية الوطنية<input required inputMode="numeric"value={form.nationalId}onChange={e=>setForm({...form,nationalId:e.target.value})}/></label></div>{error&&<div className="error">{error}</div>}<button className="primary wide"disabled={busy||!selected}>{busy?'جاري إرسال الطلب...':'تقديم طلب الانضمام'}</button></form></main>
}
function ApplicationStatus({application,onRetry,onPortal}:{application:any;onRetry:()=>void;onPortal:()=>void}){const state=application.status;const approved=state==='approved',rejected=state==='rejected';return <main className="auth application-status"><div className="auth-card"><div className={'auth-icon '+(rejected?'danger':'')}>{approved?<CheckCircle2/>:rejected?<XCircle/>:<Clock3/>}</div><span className="eyebrow">حالة طلب الانضمام</span><h1>{approved?'تم قبول طلبك':rejected?'تعذر قبول الطلب حاليًا':'طلبك تحت المراجعة'}</h1><p>{approved?`أصبحت مستفيدًا لدى ${application.charity_name} ويمكنك الآن الدخول إلى بوابتك.`:rejected?(application.rejection_reason||'راجِع سبب الرفض ثم حدّث طلبك.'):`تراجع ${application.charity_name} طلبك، وسنرسل لك إشعارًا عند تحديثه.`}</p><div className="application-meta"><span>{application.city}{application.region&&` · ${application.region}`}</span><span>قُدّم {new Date(application.created_at).toLocaleDateString('ar-SA')}</span></div>{approved&&<button className="primary wide"onClick={onPortal}>فتح بوابة المستفيد</button>}{rejected&&<button className="primary wide"onClick={onRetry}>تحديث وإعادة تقديم الطلب</button>}</div></main>}
