import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2,Eye,FileCheck2,FileUp,Loader2,ShieldCheck,Trash2,UploadCloud,XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import BackButton from '../components/BackButton';
import { supabase } from '../supabase';
import './beneficiary.css';

const labels:Record<string,string>={national_id:'الهوية الوطنية',address:'إثبات العنوان',income:'تعريف الدخل',family_card:'سجل الأسرة',iban:'شهادة الآيبان',medical:'تقرير طبي',other:'مستند إضافي'};
const required=['national_id','address'];
const allowed=['application/pdf','image/jpeg','image/png','image/webp'];
export default function BeneficiaryApplicationDocuments(){
 const n=useNavigate();const[state,setState]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=async()=>{const r=await supabase.rpc('beneficiary_application_documents_state');if(r.error)setError(r.error.message);else{const x:any=r.data||{};setState({...x,completion_percent:x.completion,documents:(x.documents||[]).map((d:any)=>({...d,file_name:d.original_name,file_size:d.size_bytes,bucket_name:d.bucket_id}))})}};
 useEffect(()=>{load()},[]);
 const documents=useMemo(()=>Array.isArray(state?.documents)?state.documents:[],[state]);
 async function upload(kind:string,file?:File){if(!file)return;if(!allowed.includes(file.type)||file.size>10*1024*1024){setError('المسموح PDF أو صورة وبحد أقصى 10MB.');return}setBusy(kind);setError('');try{const app=state?.application;if(!app?.id||!app?.charity_id)throw new Error('لا يوجد طلب انضمام صالح.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${app.charity_id}/${app.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('beneficiary-documents').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const reg=await supabase.rpc('register_beneficiary_application_document',{p_application_id:app.id,p_document_type:kind,p_original_name:file.name,p_object_path:path,p_mime_type:file.type,p_size_bytes:file.size});if(reg.error){await supabase.storage.from('beneficiary-documents').remove([path]);throw reg.error}await load()}catch(x:any){setError(x.message||'تعذر رفع المستند')}finally{setBusy('')}}
 async function view(doc:any){const r=await supabase.storage.from(doc.bucket_id||'beneficiary-documents').createSignedUrl(doc.object_path,90);if(r.error)setError(r.error.message);else window.open(r.data.signedUrl,'_blank','noopener,noreferrer')}
 async function remove(doc:any){if(!confirm('حذف هذا المستند؟'))return;setBusy(doc.id);const r=await supabase.rpc('remove_beneficiary_application_document',{p_document_id:doc.id});if(r.error)setError(r.error.message);else await load();setBusy('')}
 if(!state)return <main className="module-page"><div className="loading"><Loader2 className="spin"/> جاري تجهيز ملفك…</div></main>;
 if(!state.application)return <main className="auth"><div className="auth-card"><FileUp className="auth-icon"/><h1>ابدأ بطلب الانضمام</h1><p>اختر الجمعية أولًا، ثم ستتمكن من إرسال ملفك للمراجعة.</p><button className="primary wide" onClick={()=>n('/beneficiary-apply')}>اختيار جمعية</button></div></main>;
 const completion=Number(state.completion_percent||0);return <main className="module-page beneficiary-documents-page"><BackButton fallback="/beneficiary-apply"/><div className="module-head"><div><span className="eyebrow"><ShieldCheck size={15}/> ملف خاص ومشفّر الوصول</span><h1>مستندات طلب الانضمام</h1><p>أكمل المستندات الأساسية لترسل الجمعية ملفك وتراجعه باحترافية.</p></div><div className="document-progress"><strong>{completion}%</strong><span>اكتمال الملف</span></div></div><div className="progress-track"><i style={{width:`${completion}%`}}/></div><div className="document-note"><FileCheck2/><div><b>ماذا يحدث بعد الرفع؟</b><p>يصل المستند لفريق الجمعية فقط. قد يتم قبوله أو إعادته لك مع ملاحظة واضحة.</p></div></div>{error&&<div className="error">{error}</div>}<section className="document-upload-grid">{[...required,'income','family_card','iban','medical','other'].map(kind=>{const docs=documents.filter((d:any)=>d.document_type===kind);return <article className="document-slot" key={kind}><div className="document-slot-head"><span>{labels[kind]}</span>{required.includes(kind)?<b>مطلوب</b>:<small>اختياري</small>}</div>{docs.map((d:any)=><div className="uploaded-document" key={d.id}><span className={`doc-status ${d.review_status}`}>{d.review_status==='accepted'?<CheckCircle2/>:d.review_status==='rejected'?<XCircle/>:<FileCheck2/>}{d.review_status==='accepted'?'مقبول':d.review_status==='rejected'?'يحتاج تعديل':'قيد المراجعة'}</span><b title={d.file_name}>{d.file_name}</b>{d.review_notes&&<p>{d.review_notes}</p>}<div><button onClick={()=>view(d)}><Eye/> عرض</button>{d.review_status!=='accepted'&&<button className="danger-text" onClick={()=>remove(d)} disabled={busy===d.id}><Trash2/> حذف</button>}</div></div>)}<label className="drop-upload"><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={e=>upload(kind,e.target.files?.[0])}/>{busy===kind?<Loader2 className="spin"/>:<UploadCloud/>}<span>{busy===kind?'جاري الرفع…':'رفع مستند'}</span><small>PDF أو صورة · 10MB</small></label></article>})}</section><div className="document-actions"><button className="secondary" onClick={()=>n('/beneficiary-apply')}>عرض حالة الطلب</button>{state.application.status==='approved'&&<button className="primary" onClick={()=>n('/beneficiary')}>فتح بوابتي</button>}</div></main>
}
