import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, Clock3, FileText, HeartHandshake, UserRound, XCircle } from 'lucide-react';
import { useNavigate, useLocation } from 'react-router-dom';
import { supabase } from '../supabase';

type CaseData={id:string;case_number:string;title:string;status:string;priority:string;created_at:string;updated_at:string;beneficiary_id:string;beneficiary?:{full_name:string;phone:string|null;status:string}|null};
type Support={id:string;support_type:string;amount:number|null;quantity:number|null;status:string;notes:string|null;provided_at:string|null;created_at:string};
const statuses:Record<string,string>={new:'جديدة',under_review:'قيد المراجعة',approved:'معتمدة',rejected:'مرفوضة',closed:'مغلقة'};
const priorities:Record<string,string>={low:'منخفضة',medium:'متوسطة',high:'عالية',urgent:'عاجلة'};
export default function CaseDetails(){const id=useLocation().pathname.split('/')[2];const nav=useNavigate();const [c,setC]=useState<CaseData|null>(null);const [support,setSupport]=useState<Support[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
useEffect(()=>{load()},[id]);
async function load(){if(!id)return;setLoading(true);setError('');const {data,error}=await supabase.from('cases').select('id,case_number,title,status,priority,created_at,updated_at,beneficiary_id,beneficiary:beneficiaries(full_name,phone,status)').eq('id',id).maybeSingle();if(error||!data){setError(error?.message||'الحالة غير موجودة');setLoading(false);return}setC(data as unknown as CaseData);const r=await supabase.from('support_records').select('id,support_type,amount,quantity,status,notes,provided_at,created_at').eq('case_id',id).order('created_at',{ascending:false});setSupport((r.data||[]) as Support[]);setLoading(false)}
async function changeStatus(next:string){if(!id||!c)return;setBusy(true);setError('');const {data,error}=await supabase.rpc('transition_case',{p_case_id:id,p_status:next});if(error)setError(error.message);else if(data)setC(data as unknown as CaseData);setBusy(false)}
if(loading)return <main className="dashboard"><div className="empty">جاري تحميل تفاصيل الحالة...</div></main>;
if(!c)return <main className="dashboard"><div className="error">{error}</div></main>;
return <main className="dashboard"><button className="back-link" onClick={()=>nav('/cases')}><ArrowRight/> العودة للحالات</button><div className="dash-head"><div><div className="eyebrow">{c.case_number} · {priorities[c.priority]||c.priority}</div><h1>{c.title}</h1><p>ملف الحالة مرتبط مباشرة بملف المستفيد وسجل الدعم.</p></div><div className="action-row"><button disabled={busy||c.status==='approved'} className="primary" onClick={()=>changeStatus('approved')}><CheckCircle2/> اعتماد</button><button disabled={busy||c.status==='rejected'} className="secondary" onClick={()=>changeStatus('rejected')}><XCircle/> رفض</button></div></div><div className="detail-grid"><section className="panel"><div className="panel-title"><div><span>المستفيد</span><h2>{c.beneficiary?.full_name||'—'}</h2></div><UserRound/></div><div className="detail-list"><div><span>الهاتف</span><b>{c.beneficiary?.phone||'غير مسجل'}</b></div><div><span>حالة الملف</span><b>{c.beneficiary?.status||'—'}</b></div><div><span>حالة الطلب</span><b>{statuses[c.status]||c.status}</b></div><div><span>تاريخ الإنشاء</span><b>{new Date(c.created_at).toLocaleDateString('ar-SA')}</b></div></div></section><section className="panel"><div className="panel-title"><div><span>سجل الدعم</span><h2>ما تم تقديمه</h2></div><HeartHandshake/></div>{support.length?<div className="timeline">{support.map(s=><div className="timeline-item" key={s.id}><div className="timeline-dot"><HeartHandshake/></div><div><b>{s.support_type}</b><p>{s.amount!=null?`${s.amount.toLocaleString('ar-SA')} ر.س`:s.quantity!=null?`الكمية: ${s.quantity}`:'دعم عيني'}</p>{s.notes&&<small>{s.notes}</small>}<time>{s.provided_at?new Date(s.provided_at).toLocaleDateString('ar-SA'):new Date(s.created_at).toLocaleDateString('ar-SA')}</time></div></div>)}</div>:<div className="empty">لا يوجد دعم مسجل لهذه الحالة حتى الآن.</div>}</section></div><section className="panel"><div className="panel-title"><div><span>المراجعة</span><h2>تاريخ الحالة</h2></div><Clock3/></div><div className="status-steps"><div className="step done"><CheckCircle2/><span>تم إنشاء الطلب</span><small>{new Date(c.created_at).toLocaleDateString('ar-SA')}</small></div><div className={`step ${['under_review','approved','rejected','closed'].includes(c.status)?'done':''}`}><FileText/><span>المراجعة</span><small>{c.status==='new'?'بانتظار المراجعة':statuses[c.status]}</small></div><div className={`step ${['approved','closed'].includes(c.status)?'done':''}`}><HeartHandshake/><span>التنفيذ</span><small>{c.status==='approved'||c.status==='closed'?'جاهزة/قيد التنفيذ':'لم تبدأ بعد'}</small></div></div></section></main>}
