import {useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,HeartHandshake,Landmark} from 'lucide-react';
import {supabase} from '../supabase';
export default function CharityWebsite(){
 const {pathname}=useLocation(),navigate=useNavigate(),id=pathname.split('/')[2];
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');supabase.rpc('public_charity_site',{p_charity_id:id}).then(r=>{if(!live)return;if(r.error)setError('تعذر تحميل الموقع. حاول مرة أخرى لاحقًا.');else setData(r.data);setLoading(false)});return()=>{live=false}},[id]);
 function apply(){sessionStorage.setItem('jamaity-selected-charity',id);navigate('/beneficiary-apply?charity='+encodeURIComponent(id))}
 if(loading)return <main className="public"><p>جاري تحميل موقع الجمعية…</p></main>;
 if(error||!data)return <main className="public"><h1>{error||'الموقع غير منشور حاليًا'}</h1><button className="secondary" onClick={()=>navigate('/directory')}>دليل الجمعيات</button></main>;
 const c=data.charity,s=data.site;
 return <main className="public" dir="rtl"><section className="public-hero"><div className="seal">{c.logo_url?<img src={c.logo_url} alt="شعار الجمعية" style={{width:64,height:64,objectFit:'contain'}}/>:<Building2/>}</div><div><span>{c.region} · {c.city}</span><h1>{c.name_ar}</h1><p>{c.description_ar}</p><div className="hero-actions"><button className="secondary" onClick={apply}><HeartHandshake/> تقديم طلب استفادة</button><button className="secondary" onClick={()=>navigate('/beneficiary-login')}>دخول المستفيد</button>{s.iban&&<a className="secondary" href="#bank">التبرع بتحويل بنكي</a>}</div></div></section><nav className="sales-strip" style={{margin:'20px 0'}}><a href="#about">من نحن</a><a href="#programs">البرامج</a><a href="#news">المركز الإعلامي</a><a href="#bank">الحساب البنكي</a><a href="#contact">تواصل معنا</a></nav><section id="about" className="profile-grid">{[['رسالتنا',s.mission],['رؤيتنا',s.vision]].map(([label,value])=><article className="panel" key={label}><h2>{label}</h2><p style={{whiteSpace:'pre-wrap'}}>{value||'لم تنشر الجمعية هذا المحتوى بعد.'}</p></article>)}</section><section className="public-body" id="programs"><h2>برامجنا وخدماتنا</h2><div className="profile-grid">{String(s.programs||'').split('\n').filter(Boolean).map((p,i)=><article className="data-card" style={{padding:24}} key={i}><HeartHandshake/><h3>{p}</h3><button className="secondary" onClick={apply}>طلب الاستفادة</button></article>)}</div></section><section className="public-body" id="news"><h2>أخبار الجمعية</h2>{data.updates.length?data.updates.map((u:any)=><article className="public-body" key={u.id}><small>{new Date(u.published_at).toLocaleDateString('ar-SA')}</small><h3>{u.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{u.body}</p></article>):<p>لا توجد أخبار منشورة بعد.</p>}</section><section className="public-body" id="bank"><Landmark/><h2>ساهم بتحويل بنكي</h2>{s.iban?<><p>البنك: {s.bank_name}</p><p>صاحب الحساب: {s.bank_holder}</p><label>الآيبان<input readOnly dir="ltr" value={s.iban}/></label><p>استخدم تطبيق البنك للتحويل. احتفظ بالإيصال وتواصل مع الجمعية لتأكيد الاستلام.</p></>:<p>لم تنشر الجمعية حسابها البنكي بعد.</p>}</section><footer className="public-body" id="contact"><h2>تواصل مع {c.name_ar}</h2><p>{s.address}</p><p dir="ltr">{s.contact_phone}</p><p>{s.contact_email}</p><small>مدعوم بمنصة جمعيتي · بيانات المستفيدين ومستنداتهم غير معروضة في هذا الموقع.</small></footer></main>;
}
