import { useEffect,useState } from 'react';
import { AlertTriangle,ArrowLeft,BarChart3,CheckCircle2,HeartHandshake,RefreshCw,ShieldCheck,Users,WalletCards } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabase';
import type { AccessState } from '../lib/rbac';
import TrialCountdown from '../components/TrialCountdown';

const money=(v:any)=>Number(v||0).toLocaleString('ar-SA')+' ر.س';
export default function Dashboard({access}:{access:AccessState}){
 const n=useNavigate();const[operational,setOperational]=useState<any>({}),[commercial,setCommercial]=useState<any>({}),[attention,setAttention]=useState<any>({items:[],count:0}),[onboarding,setOnboarding]=useState<any>({steps:[],progress:0}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const[o,c,a,on]=await Promise.all([supabase.rpc('dashboard_operational_summary'),supabase.rpc('executive_commercial_summary'),supabase.rpc('attention_center'),supabase.rpc('onboarding_state')]);const failed=o.error||c.error||a.error||on.error;if(failed)setError(failed.message);else{setOperational(o.data||{});setCommercial(c.data||{});setAttention(a.data||{items:[]});setOnboarding(on.data||{steps:[]})}setLoading(false)}useEffect(()=>{void load()},[]);
 return <><TrialCountdown access={access}/><main className="dashboard"><div className="dash-head"><div><div className="eyebrow">لوحة القيادة التنفيذية</div><h1>صباح الأثر 🌿</h1><p>صورة مباشرة للتشغيل والمال والحوكمة وما يحتاج قرارك.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div>{error&&<div className="error">{error}</div>}
 {loading?<div className="loading">جاري بناء لوحة القيادة...</div>:<><div className="kpis"><K icon={<Users/>}t="المستفيدون النشطون"v={operational.beneficiaries_active}/><K icon={<HeartHandshake/>}t="قيمة الدعم المنفذ"v={money(operational.support_value_executed)}/><K icon={<WalletCards/>}t="التبرعات المستلمة"v={money(operational.donations_received_value)}/><K icon={<ShieldCheck/>}t="مؤشر الحوكمة"v={Number(commercial.governance_score||0).toLocaleString('ar-SA')+'%'}/></div>
 <div className="dashboard-core"><section className="panel attention-panel"><div className="panel-title"><div><span>أولوية العمل</span><h2>يتطلب انتباهك</h2></div><AlertTriangle/></div>{!(attention.items||[]).length?<div className="empty"><CheckCircle2/> لا توجد عناصر حرجة الآن.</div>:<div className="attention-list">{attention.items.map((x:any,i:number)=><button key={i}onClick={()=>x.action_path&&n(x.action_path)}><span className={'priority p'+(x.priority||0)}/><span><b>{x.title_ar}</b><small>{x.body_ar}</small></span><ArrowLeft/></button>)}</div>}</section>
 <section className="panel onboarding-panel"><div className="panel-title"><div><span>تهيئة الجمعية</span><h2>جهز جمعيتك خلال دقائق</h2></div><strong>{Number(onboarding.progress||0).toLocaleString('ar-SA')}%</strong></div><div className="progress-track"><i style={{width:`${onboarding.progress||0}%`}}/></div><div className="onboarding-list">{(onboarding.steps||[]).map((x:any)=><div className={x.completed?'done':''}key={x.code}>{x.completed?<CheckCircle2/>:<span/>}<div><b>{x.title_ar}</b><small>{x.description_ar}</small></div></div>)}</div></section></div>
 <div className="report-grid"><section className="panel"><h2>التشغيل</h2><Rows data={{'الحالات المفتوحة':operational.cases_open,'الدعم المعلق':operational.support_pending,'طلبات دعم المستفيدين':operational.beneficiary_requests_pending,'أعضاء الفريق':operational.team_active}}/></section><section className="panel"><h2>الإدارة والحوكمة</h2><Rows data={{'الموافقات المعلقة':commercial.approvals_pending,'متطلبات متأخرة':commercial.governance_overdue,'إشعارات غير مقروءة':commercial.unread_notifications,'اكتمال الإعداد':(commercial.onboarding_progress||0)+'%'}}/></section></div></>}</main></>
}
function K({icon,t,v}:{icon:React.ReactNode;t:string;v:any}){return <div className="kpi"><div className="kpi-icon">{icon}</div><span>{t}</span><strong>{typeof v==='number'?v.toLocaleString('ar-SA'):v}</strong><small>تحديث مباشر</small></div>}
function Rows({data}:{data:Record<string,any>}){return <div className="detail-list">{Object.entries(data).map(([k,v])=><div key={k}><span>{k}</span><strong>{Number.isFinite(v)?Number(v).toLocaleString('ar-SA'):v}</strong></div>)}</div>}
