import { useEffect,useMemo,useState } from 'react';
import { Building2,Heart,Mail,Phone,Plus,Search,ShieldCheck,UserRound } from 'lucide-react';
import { supabase } from '../supabase';

const donorLabels:Record<string,string>={individual:'فرد',company:'شركة',foundation:'مؤسسة مانحة'};
export default function Donors(){
 const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',type:'individual',phone:'',email:''});
 async function load(){setLoading(true);setError('');const r=await supabase.from('donors').select('*,donations(amount,status,donated_at)').order('created_at',{ascending:false}).limit(200);if(r.error)setError(r.error.message);else setRows(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(x=>`${x.full_name||''} ${x.phone||''} ${x.email||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=await supabase.rpc('create_donor',{p_full_name:form.name.trim(),p_donor_type:form.type,p_phone:form.phone.trim()||null,p_email:form.email.trim()||null});if(r.error)setError(r.error.message);else{setOpen(false);setForm({name:'',type:'individual',phone:'',email:''});await load()}setBusy(false)}
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><Heart size={15}/> إدارة العلاقات</span><h1>المتبرعون</h1><p>ملف موحد لكل متبرع مع بيانات التواصل وتاريخ المساهمات.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/> متبرع جديد</button></div><div className="module-toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو الجوال أو البريد..."/></div></div>{error&&<div className="error">{error}</div>}<section className="data-card"><div className="data-card-head"><strong>{shown.length.toLocaleString('ar-SA')} متبرع</strong><span><ShieldCheck size={14}/> بيانات معزولة حسب الجمعية</span></div>{loading?<div className="empty">جاري تحميل سجل المتبرعين...</div>:!shown.length?<div className="empty"><Heart size={34}/> لا توجد سجلات بعد. أضف أول متبرع.</div>:<div className="support-list">{shown.map(x=>{const ds=(x.donations||[]).filter((d:any)=>d.status!=='rejected');const total=ds.reduce((s:number,d:any)=>s+Number(d.amount||0),0);return <article className="support-row" key={x.id}><div className="support-icon">{x.donor_type==='individual'?<UserRound/>:<Building2/>}</div><div className="support-main"><b>{x.full_name}</b><span>{donorLabels[x.donor_type]||x.donor_type}</span><small>{x.phone||x.email||'لا توجد بيانات تواصل'}</small></div><div className="support-value"><strong>{total.toLocaleString('ar-SA')} ر.س</strong><small>{ds.length.toLocaleString('ar-SA')} تبرع</small></div><div className="donor-contact">{x.phone&&<a href={`tel:${x.phone}`} title={x.phone}><Phone size={16}/></a>}{x.email&&<a href={`mailto:${x.email}`} title={x.email}><Mail size={16}/></a>}</div></article>})}</div>}</section>{open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><form className="modal" onSubmit={create}><div className="modal-head"><div><b>إضافة متبرع جديد</b><span>أنشئ ملف العلاقة أولًا ثم أضف تبرعاته النقدية أو العينية.</span></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>اسم المتبرع أو الجهة<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>نوع المتبرع<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="individual">فرد</option><option value="company">شركة</option><option value="foundation">مؤسسة مانحة</option></select></label><div className="form-grid"><label>رقم الجوال<input inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>البريد الإلكتروني<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><button className="primary wide" disabled={busy}>{busy?'جاري الحفظ…':'حفظ ملف المتبرع'}</button></form></div>}</main>
}
