import { useEffect,useState } from 'react';
import { CalendarDays,CheckCircle2,FileUp,RefreshCw,ShieldCheck } from 'lucide-react';
import { supabase } from '../supabase';
import { getAccessState } from '../lib/rbac';

const labels:Record<string,string>={not_started:'غير مبدوء',in_progress:'جاري',ready:'جاهز',not_applicable:'غير منطبق'};
export default function Governance(){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){setError('');const r=await supabase.rpc('governance_center');if(r.error)setError(r.error.message);else setData(r.data)}
 useEffect(()=>{void load()},[]);
 async function change(id:string,status:string,due?:string){setBusy(id);const r=await supabase.rpc('set_governance_requirement_status',{p_requirement_id:id,p_status:status,p_due_date:due||null});if(r.error)setError(r.error.message);else await load();setBusy('')}
 async function upload(item:any,file?:File){if(!file)return;if(file.size>10*1024*1024)return setError('الحد الأقصى للملف 10MB.');if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))return setError('نوع الملف غير مسموح.');setBusy(item.id);setError('');const access=await getAccessState();if(!access.charityId){setBusy('');return setError('لا توجد جمعية فعالة.')}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${access.charityId}/${item.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('governance-evidence').upload(path,file,{contentType:file.type,upsert:false});if(up.error){setBusy('');return setError(up.error.message)}const rpc=await supabase.rpc('add_governance_evidence',{p_requirement_id:item.id,p_title_ar:file.name,p_object_path:path,p_expires_at:null,p_notes:null});if(rpc.error){await supabase.storage.from('governance-evidence').remove([path]);setError(rpc.error.message)}else await load();setBusy('')}
 if(!data)return <main className="module-page"><div className="loading">جاري تحميل مركز الحوكمة...</div>{error&&<div className="error">{error}</div>}</main>;
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><ShieldCheck/> الحوكمة والامتثال</span><h1>مركز الحوكمة</h1><p>متابعة المتطلبات والشواهد والاستحقاقات من مصدر بيانات واحد.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div>{error&&<div className="error">{error}</div>}<section className="governance-summary"><div className="progress-ring"style={{'--progress':`${data.score}%`}as React.CSSProperties}><strong>{Number(data.score).toLocaleString('ar-SA')}%</strong><span>مؤشر الحوكمة</span></div><div><b>{data.ready} جاهز</b><span>من {data.total} متطلبات</span></div><div><b>{data.overdue} متأخر</b><span>يتطلب معالجة</span></div></section><section className="governance-grid">{(data.items||[]).map((item:any)=><article className="governance-item"key={item.id}><div className="governance-item-head"><span>{item.category}</span><span className={'status '+(item.status==='ready'?'active':'inactive')}>{labels[item.status]||item.status}</span></div><h3>{item.title_ar}</h3><p>{item.description_ar}</p><div className="governance-meta"><span><CalendarDays/> {item.due_date?new Date(item.due_date).toLocaleDateString('ar-SA'):'بلا موعد'}</span><span><FileUp/> {item.evidence_count} شاهد</span></div><div className="action-row"><select value={item.status}disabled={busy===item.id}onChange={e=>change(item.id,e.target.value,item.due_date)}><option value="not_started">غير مبدوء</option><option value="in_progress">جاري</option><option value="ready">جاهز</option><option value="not_applicable">غير منطبق</option></select><label className="secondary file-button"><FileUp/> رفع شاهد<input type="file"accept=".pdf,.jpg,.jpeg,.png,.webp"onChange={e=>upload(item,e.target.files?.[0])}/></label>{item.status==='ready'&&<CheckCircle2/>}</div></article>)}</section></main>
}
