import { useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, Clock3, PauseCircle, RefreshCw, Search, Settings2, ShieldAlert, TimerReset, XCircle, Zap } from 'lucide-react';
import { supabase } from '../supabase';

type Charity = { id:string; name_ar:string; name_en?:string; city?:string; region?:string; status:string; verified_at?:string; subscription_status?:string; subscription_ends_at?:string; subscription_plan?:string };
const fmt=(value?:string)=>value?new Date(value).toLocaleDateString('ar-SA',{year:'numeric',month:'short',day:'numeric'}):'—';
const labels:Record<string,string>={pending:'قيد المراجعة',approved:'معتمدة',suspended:'موقوفة',rejected:'مرفوضة',trial:'تجريبية',active:'نشطة',paused:'متوقفة مؤقتًا',expired:'منتهية',cancelled:'ملغاة'};
const label=(value?:string)=>labels[value||'']||'غير مفعلة';

export default function PlatformAdmin(){
 const[rows,setRows]=useState<Charity[]>([]),[defaultDays,setDefaultDays]=useState(14),[trialDays,setTrialDays]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('all');
 async function load(){setLoading(true);setError('');const[list,settings]=await Promise.all([supabase.rpc('platform_list_charities'),supabase.rpc('platform_trial_settings')]);if(list.error||settings.error)setError((list.error||settings.error)?.message||'تعذر تحميل مركز المنصة');setRows((list.data||[])as Charity[]);setDefaultDays(Number((settings.data as any)?.default_trial_days||14));setLoading(false)}
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>({total:rows.length,pending:rows.filter(x=>x.status==='pending').length,approved:rows.filter(x=>x.status==='approved').length,suspended:rows.filter(x=>x.status==='suspended').length,trial:rows.filter(x=>x.subscription_status==='trial').length,active:rows.filter(x=>x.subscription_status==='active').length}),[rows]);
 const shown=useMemo(()=>rows.filter(x=>{const text=`${x.name_ar||''} ${x.name_en||''} ${x.city||''} ${x.region||''}`.toLowerCase();return text.includes(q.trim().toLowerCase())&&(filter==='all'||x.status===filter||x.subscription_status===filter)}),[rows,q,filter]);
 async function run(key:string,action:()=>PromiseLike<{error:any}>,success:string){setBusy(key);setError('');setNotice('');const result=await action();if(result.error)setError(result.error.message);else{setNotice(success);await load()}setBusy('')}
 const changeStatus=(id:string,status:string)=>run(id+status,()=>supabase.rpc('platform_set_charity_status',{p_charity_id:id,p_status:status}),'تم تحديث حالة الجمعية.');
 const changeSubscription=(row:Charity,status:string,days=0)=>{const base=row.subscription_ends_at&&new Date(row.subscription_ends_at)>new Date()?new Date(row.subscription_ends_at):new Date();const end=['paused','suspended','cancelled','expired'].includes(status)?row.subscription_ends_at||null:new Date(base.getTime()+days*86400000).toISOString();return run(row.id+status,()=>supabase.rpc('platform_set_subscription',{p_charity_id:row.id,p_status:status,p_ends_at:end,p_notes:'تم التحديث من مركز إدارة المنصة'}),'تم تحديث الاشتراك.')};
 const changeTrial=(row:Charity,restart:boolean)=>{const days=trialDays[row.id]||defaultDays;if(restart&&!window.confirm('سيبدأ عداد التجربة من الآن. هل تريد إعادة تشغيل التجربة؟'))return;void run(row.id+'trial',async()=>{if(row.subscription_status==='expired'){const activate=await supabase.rpc('platform_set_subscription',{p_charity_id:row.id,p_status:'trial',p_ends_at:new Date().toISOString(),p_notes:'إعادة تشغيل التجربة من مركز المنصة'});if(activate.error)return activate}return supabase.rpc('platform_set_trial_duration',{p_charity_id:row.id,p_days:days,p_restart:restart})},restart?'أعيد تشغيل الفترة التجريبية.':'تم تعديل المدة مع الحفاظ على تاريخ البداية.')};
 const saveDefault=()=>run('default-trial',()=>supabase.rpc('platform_set_default_trial_days',{p_days:defaultDays}),'تم حفظ مدة التجربة الافتراضية.');
 return <main className="module-page platform-admin"><div className="module-head"><div><span className="eyebrow"><ShieldAlert size={15}/> مركز تحكم المنصة</span><h1>إدارة جمعيتي</h1><p>اعتماد الجمعيات والتحكم في التجارب والاشتراكات من مساحة مستقلة وآمنة.</p></div><button className="secondary"onClick={load}disabled={loading}><RefreshCw size={18}/> تحديث</button></div>{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 <section className="stats-grid"><Stat icon={<Building2/>}label="إجمالي الجمعيات"value={stats.total}/><Stat icon={<Clock3/>}label="قيد المراجعة"value={stats.pending}/><Stat icon={<CheckCircle2/>}label="معتمدة"value={stats.approved}/><Stat icon={<PauseCircle/>}label="موقوفة"value={stats.suspended}/><Stat icon={<TimerReset/>}label="تجريبية"value={stats.trial}/><Stat icon={<Zap/>}label="اشتراك نشط"value={stats.active}/></section>
 <section className="data-card platform-settings"><div><Settings2/><div><b>إعداد الفترة التجريبية</b><p>تبدأ تلقائيًا لحظة تسجيل الجمعية، وليس عند الاعتماد.</p></div></div><label>المدة الافتراضية<input type="number"min={1}max={3650}value={defaultDays}onChange={e=>setDefaultDays(Number(e.target.value))}/><span>يومًا</span></label><button className="primary small"disabled={!!busy}onClick={saveDefault}>حفظ</button></section>
 <section className="data-card"><div className="data-card-head"><strong>الجمعيات والاشتراكات</strong><span>{shown.length.toLocaleString('ar-SA')} نتيجة</span></div><div className="module-toolbar"><div className="search-box"><Search size={18}/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="ابحث باسم الجمعية أو المدينة..."/></div><select value={filter}onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option><option value="pending">قيد المراجعة</option><option value="approved">معتمدة</option><option value="suspended">موقوفة</option><option value="rejected">مرفوضة</option><option value="trial">تجريبية</option><option value="active">نشطة</option><option value="expired">منتهية</option></select></div>
 {loading?<div className="empty">جاري تحميل بيانات المنصة...</div>:!shown.length?<div className="empty"><Building2 size={36}/>لا توجد نتائج مطابقة.</div>:<div className="platform-list">{shown.map(row=><article className="platform-charity"key={row.id}><div className="platform-charity-head"><div className="person"><div className="person-avatar"><Building2 size={17}/></div><div><b>{row.name_ar}</b><small>{[row.city,row.region].filter(Boolean).join(' · ')||'المملكة العربية السعودية'}</small></div></div><div className="status-stack"><span className={'status '+(row.status==='approved'?'active':row.status==='suspended'?'blocked':'inactive')}>{label(row.status)}</span><span className="status inactive">{label(row.subscription_status)}</span></div></div><div className="platform-subscription"><div><span>الخطة</span><b>{row.subscription_plan||'—'}</b></div><div><span>انتهاء الاشتراك</span><b>{fmt(row.subscription_ends_at)}</b></div><div><span>تاريخ الاعتماد</span><b>{fmt(row.verified_at)}</b></div></div>
 <div className="action-row">{row.status!=='approved'&&<button className="secondary"disabled={!!busy}onClick={()=>changeStatus(row.id,'approved')}><CheckCircle2 size={15}/> اعتماد</button>}{row.status==='approved'&&<button className="secondary"disabled={!!busy}onClick={()=>changeStatus(row.id,'suspended')}><PauseCircle size={15}/> تعليق الجمعية</button>}{row.status==='suspended'&&<button className="secondary"disabled={!!busy}onClick={()=>changeStatus(row.id,'approved')}>إعادة التفعيل</button>}{row.status==='pending'&&<button className="danger-button"disabled={!!busy}onClick={()=>changeStatus(row.id,'rejected')}><XCircle size={15}/> رفض</button>}<button className="primary small"disabled={!!busy}onClick={()=>changeSubscription(row,'active',30)}>تمديد 30 يومًا</button><button className="secondary"disabled={!!busy}onClick={()=>changeSubscription(row,'paused')}>إيقاف مؤقت</button><button className="secondary"disabled={!!busy}onClick={()=>changeSubscription(row,'suspended')}>تعليق الاشتراك</button></div>
 {['trial','expired'].includes(row.subscription_status||'')&&<div className="trial-controls"><label>مدة التجربة<input type="number"min={1}max={3650}value={trialDays[row.id]||defaultDays}onChange={e=>setTrialDays({...trialDays,[row.id]:Number(e.target.value)})}/><span>يومًا</span></label><button className="secondary"disabled={!!busy}onClick={()=>changeTrial(row,false)}>تعديل المدة</button><button className="secondary"disabled={!!busy}onClick={()=>changeTrial(row,true)}><TimerReset size={15}/> إعادة بدء التجربة</button></div>}</article>)}</div>}</section></main>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <article className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value.toLocaleString('ar-SA')}</strong></div></article>}
