import{useEffect,useMemo,useState}from'react';import{Building2,CheckCircle2,Clock3,PauseCircle,RefreshCw,Search,ShieldAlert,TimerReset,XCircle,Zap}from'lucide-react';import{supabase}from'../supabase';

type Charity={id:string;name_ar:string;name_en?:string;city?:string;region?:string;status:string;verified_at?:string;subscription_status?:string;subscription_ends_at?:string;subscription_plan?:string};
const fmt=(v?:string)=>v?new Date(v).toLocaleDateString('ar-SA',{year:'numeric',month:'short',day:'numeric'}):'—';
export default function PlatformAdmin(){const[rows,setRows]=useState<Charity[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('all');
async function load(){setLoading(true);setError('');const{data,error}=await supabase.rpc('platform_list_charities');if(error)setError(error.message);setRows((data||[]) as Charity[]);setLoading(false)}useEffect(()=>{void load()},[]);
const stats=useMemo(()=>({total:rows.length,pending:rows.filter(x=>x.status==='pending').length,approved:rows.filter(x=>x.status==='approved').length,suspended:rows.filter(x=>x.status==='suspended').length,trial:rows.filter(x=>x.subscription_status==='trial').length,active:rows.filter(x=>x.subscription_status==='active').length,expired:rows.filter(x=>['expired','cancelled'].includes(x.subscription_status||'')).length}),[rows]);
const shown=useMemo(()=>rows.filter(x=>{const text=`${x.name_ar||''} ${x.name_en||''} ${x.city||''} ${x.region||''}`.toLowerCase();const match=text.includes(q.toLowerCase());const state=filter==='all'||(filter==='subscription'?(x.subscription_status||'none'):(x.status||'none'))===filter;return match&&state}),[rows,q,filter]);
async function status(id:string,s:string){setBusy(id+s);setError('');const{error}=await supabase.rpc('platform_set_charity_status',{p_charity_id:id,p_status:s});if(error)setError(error.message);else await load();setBusy('')}
async function subscription(id:string,s:string,days=30){setBusy(id+s+days);setError('');const row=rows.find(x=>x.id===id);const base=row?.subscription_ends_at&&new Date(row.subscription_ends_at)>new Date()?new Date(row.subscription_ends_at):new Date();const end=s==='paused'||s==='suspended'?row?.subscription_ends_at||null:new Date(base.getTime()+days*86400000).toISOString();const{error}=await supabase.rpc('platform_set_subscription',{p_charity_id:id,p_status:s,p_ends_at:end,p_notes:null});if(error)setError(error.message);else await load();setBusy('')}
return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><ShieldAlert size={15}/> مركز تحكم المنصة</span><h1>Super Admin Control Center</h1><p>اعتماد الجمعيات وإدارة دورة حياة الاشتراكات من طبقة المنصة الآمنة.</p></div><button className="secondary"onClick={load}disabled={loading}><RefreshCw size={18}/> تحديث</button></div>{error&&<div className="error">{error}</div>}
<section className="stats-grid"><Stat icon={<Building2/>}label="إجمالي الجمعيات"value={stats.total}/><Stat icon={<Clock3/>}label="قيد المراجعة"value={stats.pending}/><Stat icon={<CheckCircle2/>}label="معتمدة"value={stats.approved}/><Stat icon={<PauseCircle/>}label="موقوفة"value={stats.suspended}/><Stat icon={<TimerReset/>}label="تجريبية"value={stats.trial}/><Stat icon={<Zap/>}label="نشطة"value={stats.active}/></section>
<section className="data-card"><div className="data-card-head"><strong>إدارة الجمعيات</strong><span>{shown.length.toLocaleString('ar-SA')} نتيجة</span></div><div className="module-toolbar"><div className="search-box"><Search size={18}/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="ابحث باسم الجمعية أو المدينة أو المنطقة..."/></div><select value={filter}onChange={e=>setFilter(e.target.value)}><option value="all">كل الحالات</option><option value="pending">قيد المراجعة</option><option value="approved">معتمدة</option><option value="suspended">موقوفة</option><option value="rejected">مرفوضة</option><option value="trial">اشتراك تجريبي</option><option value="active">اشتراك نشط</option><option value="expired">اشتراك منتهي</option></select></div>
{loading?<div className="empty">جاري تحميل بيانات المنصة...</div>:!shown.length?<div className="empty"><Building2 size={36}/>لا توجد نتائج مطابقة.</div>:<div className="table-wrap"><table><thead><tr><th>الجمعية</th><th>الموقع</th><th>الاعتماد</th><th>الاشتراك</th><th>إجراءات المنصة</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><div className="person"><div className="person-avatar"><Building2 size={17}/></div><div><b>{x.name_ar}</b><small>{x.name_en||'جمعية مسجلة على المنصة'}</small></div></div></td><td>{[x.city,x.region].filter(Boolean).join(' · ')||'—'}</td><td><span className={'status '+(x.status==='approved'?'active':x.status==='suspended'?'blocked':'inactive')}>{x.status==='approved'?'معتمدة':x.status==='suspended'?'موقوفة':x.status==='rejected'?'مرفوضة':'قيد المراجعة'}</span>{x.verified_at&&<small style={{display:'block',marginTop:4}}>اعتمدت {fmt(x.verified_at)}</small>}</td><td><b>{x.subscription_status==='trial'?'تجريبي':x.subscription_status==='active'?'نشط':x.subscription_status==='paused'?'متوقف مؤقتًا':x.subscription_status==='suspended'?'موقوف':x.subscription_status==='expired'?'منتهي':x.subscription_status==='cancelled'?'ملغي':'غير مفعّل'}</b>{x.subscription_ends_at&&<small style={{display:'block',marginTop:4}}>ينتهي {fmt(x.subscription_ends_at)}</small>}</td><td><div className="action-row">{x.status!=='approved'&&<button className="secondary"disabled={!!busy}onClick={()=>status(x.id,'approved')}><CheckCircle2 size={15}/> اعتماد</button>}{x.status==='approved'&&<button className="secondary"disabled={!!busy}onClick={()=>status(x.id,'suspended')}><PauseCircle size={15}/> تعليق</button>}{x.status==='suspended'&&<button className="secondary"disabled={!!busy}onClick={()=>status(x.id,'approved')}><CheckCircle2 size={15}/> إعادة تفعيل</button>}{x.status!=='rejected'&&x.status!=='approved'&&<button className="secondary"disabled={!!busy}onClick={()=>status(x.id,'rejected')}><XCircle size={15}/> رفض</button>}{x.status==='approved'&&<><button className="primary small"disabled={!!busy}onClick={()=>subscription(x.id,'active',30)}>+30 يوم</button><button className="secondary"disabled={!!busy}onClick={()=>subscription(x.id,'active',60)}>+60</button><button className="secondary"disabled={!!busy}onClick={()=>subscription(x.id,'paused',0)}>إيقاف مؤقت</button></>}</div></td></tr>)}</tbody></table></div>}</section></main>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <article className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value.toLocaleString('ar-SA')}</strong></div></article>}