import { useEffect,useState } from 'react';
import { BarChart3,CalendarDays,FileText,RefreshCw } from 'lucide-react';
import { supabase } from '../supabase';

const money=(v:any)=>Number(v||0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})+' ر.س';
export default function Reports(){
 const today=new Date().toISOString().slice(0,10),start=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);const[from,setFrom]=useState(start),[to,setTo]=useState(today),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const r=await supabase.rpc('monthly_management_report',{p_from:new Date(from).toISOString(),p_to:new Date(to+'T23:59:59').toISOString()});if(r.error)setError(r.error.message);else setData(r.data);setLoading(false)}useEffect(()=>{void load()},[]);
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><FileText/> التقارير الإدارية</span><h1>مركز التقارير</h1><p>ملخص تشغيلي ومالي وحوكمي للفترة المختارة.</p></div><button className="secondary"onClick={load}><RefreshCw/> تحديث</button></div><section className="data-card report-filter"><CalendarDays/><label>من<input type="date"value={from}onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date"value={to}onChange={e=>setTo(e.target.value)}/></label><button className="primary small"onClick={load}>إنشاء التقرير</button></section>{error&&<div className="error">{error}</div>}{loading?<div className="loading">جاري إنشاء التقرير...</div>:data&&<><div className="kpis"><Metric t="التبرعات المستلمة"v={money(data.operational?.donations_received_value)}/><Metric t="الدعم المنفذ"v={money(data.operational?.support_value_executed)}/><Metric t="الفائض/العجز"v={money(data.financial?.surplus)}/><Metric t="الحوكمة"v={Number(data.governance?.score||0).toLocaleString('ar-SA')+'%'}/></div><div className="report-grid"><section className="panel"><h2>الملخص التشغيلي</h2><Rows data={{'إجمالي المستفيدين':data.operational?.beneficiaries_total,'الحالات المفتوحة':data.operational?.cases_open,'الدعم المعلق':data.operational?.support_pending,'طلبات المستفيدين':data.operational?.beneficiary_requests_pending,'أعضاء الفريق':data.operational?.team_active}}/></section><section className="panel"><h2>الملخص المالي</h2><Rows data={{'الإيرادات':money(data.financial?.revenue),'المصروفات':money(data.financial?.expense),'الفائض / العجز':money(data.financial?.surplus)}}/></section><section className="panel"><h2>الحوكمة</h2><Rows data={{'المتطلبات':data.governance?.total,'الجاهز':data.governance?.ready,'المتأخر':data.governance?.overdue,'المؤشر':Number(data.governance?.score||0).toLocaleString('ar-SA')+'%'}}/></section><section className="panel"><h2>المخزون</h2><Rows data={{'الأصناف':data.operational?.inventory_items,'أرصدة المستودعات':data.inventory_balances?.length||0}}/></section></div></>}</main>
}
function Metric({t,v}:{t:string;v:string}){return <div className="kpi"><div className="kpi-icon"><BarChart3/></div><span>{t}</span><strong>{v}</strong><small>للفترة المختارة</small></div>}
function Rows({data}:{data:Record<string,any>}){return <div className="detail-list">{Object.entries(data).map(([k,v])=><div key={k}><span>{k}</span><strong>{v??0}</strong></div>)}</div>}
