import { useEffect,useMemo,useRef,useState } from 'react';
import { ShieldCheck,Users,UserPlus,KeyRound,Check,X,Plus,BriefcaseBusiness } from 'lucide-react';
import { supabase } from '../supabase';
import { friendlyError } from '../lib/requests';
import { getAccessState,can } from '../lib/rbac';

import TeamInvitationForm from '../components/TeamInvitationForm';

type Member=any;
export default function Team(){
 const[charity,setCharity]=useState<any>(null),[invitations,setInvitations]=useState<any[]>([]);
 const[members,setMembers]=useState<Member[]>([]),[roles,setRoles]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[overrides,setOverrides]=useState<any[]>([]),[rolePerms,setRolePerms]=useState<any[]>([]),[access,setAccess]=useState<any>(null),[selected,setSelected]=useState<Member|null>(null),[selectedRole,setSelectedRole]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[showRoleForm,setShowRoleForm]=useState(false),[showInvite,setShowInvite]=useState(false),[roleName,setRoleName]=useState(''),[roleNameEn,setRoleNameEn]=useState('');
 const mutationLock=useRef(false);
 async function load(refresh=false){if(!refresh)setLoading(true);setError('');try{const a=await getAccessState(true);const{data:{user}}=await supabase.auth.getUser();setAccess({...a,userId:user?.id});if(!a.charityId){setLoading(false);return}const[m,p]=await Promise.all([supabase.rpc('team_center'),supabase.from('permissions').select('id,code,name_ar,name_en').order('code')]);if(m.error)throw m.error;if(p.error)throw p.error;const{data:r,error:re}=await supabase.rpc('list_manageable_roles');if(re)throw re;setMembers(m.data?.members||[]);setCharity(m.data?.charity);setInvitations(m.data?.invitations||[]);setRoles(r||[]);setPermissions(p.data||[]);if(selected){const fresh=(m.data?.members||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e:any){setError(friendlyError(e))}finally{setLoading(false)}}
 async function loadOverrides(member:Member){setSelected(member);setSelectedRole(null);setError('');const{data,error:e}=await supabase.from('user_permission_overrides').select('permission_id,effect').eq('charity_member_id',member.id);if(e)setError(friendlyError(e));else setOverrides(data||[])}
 async function loadRolePermissions(role:any){setSelectedRole(role);setSelected(null);const{data,error:e}=await supabase.from('role_permissions').select('permission_id').eq('role_id',role.id);if(e)setError(friendlyError(e));else setRolePerms(data||[])}
 useEffect(()=>{void load()},[]);
 async function mutate(key:string,action:()=>Promise<void>){
  if(mutationLock.current)return;mutationLock.current=true;setSaving(key);setError('');
  try{await action();}catch(e){setError(friendlyError(e));}finally{mutationLock.current=false;setSaving('');}
 }
 async function changeRole(member:Member,roleId:string){if(!access?.charityId||!can(access,'team.manage')||member.user_id===access.userId)return;await mutate('role',async()=>{const r=await supabase.rpc('change_member_role',{p_member_id:member.id,p_role_id:roleId});if(r.error)throw r.error;await load(true);});}
 async function setPermission(permissionId:string,effect:'allow'|'deny'){if(!selected||!can(access||{permissions:[]},'team.manage')||selected.user_id===access?.userId)return;await mutate(permissionId+effect,async()=>{const r=await supabase.rpc('set_member_permission',{p_member_id:selected.id,p_permission_id:permissionId,p_effect:effect});if(r.error)throw r.error;await loadOverrides(selected);});}
 async function setRolePermission(permissionId:string,enabled:boolean){if(!selectedRole||!can(access||{permissions:[]},'roles.manage')||selectedRole.is_system)return;await mutate('rp'+permissionId,async()=>{const r=await supabase.rpc('set_role_permission',{p_role_id:selectedRole.id,p_permission_id:permissionId,p_enabled:enabled});if(r.error)throw r.error;await loadRolePermissions(selectedRole);});}
 async function createRole(){if(!can(access||{permissions:[]},'roles.manage')||!roleName.trim())return;await mutate('newrole',async()=>{const r=await supabase.rpc('create_custom_role',{p_name_ar:roleName.trim(),p_name_en:roleNameEn.trim()||null});if(r.error)throw r.error;setShowRoleForm(false);setRoleName('');setRoleNameEn('');await load(true);});}
 async function revoke(id:string){await mutate(id,async()=>{const r=await supabase.rpc('revoke_staff_invitation',{p_id:id});if(r.error)throw r.error;await load(true);});}
 const overrideMap=useMemo(()=>Object.fromEntries(overrides.map(x=>[x.permission_id,x.effect])),[overrides]);
 const rolePermissionSet=useMemo(()=>new Set(rolePerms.map(x=>x.permission_id)),[rolePerms]);
 if(loading)return <main className="module-page"><div className="loading">جاري تحميل فريق الجمعية...</div></main>;
 const manageable=can(access||{permissions:[]},'team.manage'),roleManage=can(access||{permissions:[]},'roles.manage');
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><Users size={15}/> الحوكمة والصلاحيات</span><h1>فريق الجمعية</h1><p>إدارة الموظفين والأدوار والصلاحيات من مكان واحد.</p></div><div style={{display:'flex',gap:8}}><button className="ghost" disabled={!roleManage} onClick={()=>setShowRoleForm(true)}><BriefcaseBusiness size={17}/> دور مخصص</button><button className="primary" disabled={!manageable} onClick={()=>{setError('');setShowInvite(true)}}><UserPlus size={18}/> دعوة موظف جديد</button></div></div>{error&&<div role="alert" className="error">{error}</div>}
 <section className="panel"><h2>هوية مساحة العمل</h2><p>{charity?.name_ar}</p><label>كود الجمعية<input readOnly dir="ltr" value={charity?.charity_code||''}/></label><p>شارك رابط الدعوة الشخصي مع الموظف. الدور والبريد والجمعية تُراجع على الخادم؛ الكود وحده لا يسمح بالانضمام.</p></section>
 <div className="kpis"><div className="kpi"><div className="kpi-icon"><Users/></div><span>أعضاء الفريق</span><strong>{members.length}</strong></div><div className="kpi"><div className="kpi-icon"><KeyRound/></div><span>الصلاحيات المتاحة</span><strong>{permissions.length}</strong></div><div className="kpi"><div className="kpi-icon"><ShieldCheck/></div><span>الأدوار</span><strong>{roles.length}</strong></div></div>
 {showInvite&&<TeamInvitationForm roles={roles} onClose={()=>setShowInvite(false)} onCreated={()=>void load(true)}/>}
 {showRoleForm&&<section className="data-card" style={{marginTop:16}}><div className="data-card-head"><strong>إنشاء دور مخصص</strong><button className="ghost" onClick={()=>setShowRoleForm(false)}>إغلاق</button></div><div className="form-grid"><label>اسم الدور بالعربية<input value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder="مثال: مسؤول المستفيدين"/></label><label>اسم الدور بالإنجليزية<input value={roleNameEn} onChange={e=>setRoleNameEn(e.target.value)} placeholder="Beneficiaries Officer"/></label></div><div style={{marginTop:12}}><button className="primary" disabled={saving==='newrole'||!roleName.trim()} onClick={()=>void createRole()}>{saving==='newrole'?'جاري الإنشاء...':'إنشاء الدور'}</button></div></section>}
 <section className="panel"><h2>الدعوات</h2>{!invitations.length?<p>لا توجد دعوات بعد.</p>:<div className="table-wrap"><table><thead><tr><th>البريد</th><th>الدور</th><th>الحالة</th><th>الانتهاء</th><th>الإجراء</th></tr></thead><tbody>{invitations.map(i=><tr key={i.id}><td>{i.email}</td><td>{i.role_name}</td><td>{{pending:'بانتظار الموظف',accepted:'مقبولة',revoked:'ملغاة',expired:'منتهية'}[i.status as string]}</td><td>{new Date(i.expires_at).toLocaleDateString('ar-SA')}</td><td>{i.status==='pending'&&manageable&&<button className="secondary" disabled={saving===i.id} onClick={()=>void revoke(i.id)}>إلغاء الدعوة</button>}</td></tr>)}</tbody></table></div>}</section>
 <div className="split-layout" style={{marginTop:16}}><section className="data-card"><div className="data-card-head"><strong>أعضاء الفريق</strong><span>اختر عضوًا لإدارة صلاحياته</span></div><div className="table-wrap"><table><thead><tr><th>العضو</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>{members.map(m=><tr key={m.id} className={selected?.id===m.id?'selected-row':''}><td><div className="person"><div className="person-avatar"><Users size={17}/></div><div><b>{m.full_name||m.email||'موظف'}</b><small>{m.email}</small></div></div></td><td><select disabled={!manageable||m.user_id===access?.userId||saving==='role'} value={m.role_id||''} onChange={e=>void changeRole(m,e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.name_ar}</option>)}</select></td><td><span className={'status '+(m.status==='active'?'active':'inactive')}>{m.status==='active'?'نشط':'غير نشط'}</span></td><td><button className="ghost" onClick={()=>void loadOverrides(m)}>صلاحيات فردية</button></td></tr>)}</tbody></table></div></section>
 <section className="data-card"><div className="data-card-head"><div><strong>{selected?'صلاحيات العضو':'إدارة الأدوار'}</strong><span>{selected?'التعديل الفردي يتغلب على صلاحيات الدور':'اختر دورًا لمراجعة صلاحياته'}</span></div>{selected&&<span className="status active">{selected.roles?.name_ar||'عضو'}</span>}</div>{selected?<div className="permission-list">{selected.user_id===access?.userId&&<p>لا يمكنك تعديل صلاحيات حسابك بنفسك.</p>}{permissions.map(p=>{const ov=overrideMap[p.id];return <div className="permission-row" key={p.id}><div><b>{p.name_ar}</b><small>{p.code}</small></div><div className="permission-actions"><button className={ov==='allow'?'permission allow':'permission'} disabled={!manageable||selected.user_id===access?.userId||!!saving} onClick={()=>void setPermission(p.id,'allow')}><Check size={15}/> سماح</button><button className={ov==='deny'?'permission deny':'permission'} disabled={!manageable||selected.user_id===access?.userId||!!saving} onClick={()=>void setPermission(p.id,'deny')}><X size={15}/> منع</button><span className="permission-state">{ov==='allow'?'مسموح فرديًا':ov==='deny'?'ممنوع فرديًا':'من الدور'}</span></div></div>})}</div>:<div className="permission-list">{roles.map(r=><div className="permission-row" key={r.id}><div><b>{r.name_ar}</b><small>{r.is_system?'دور نظامي':'دور مخصص للجمعية'}</small></div><div className="permission-actions"><button className="ghost" onClick={()=>void loadRolePermissions(r)}>صلاحيات الدور</button></div></div>)}</div>}</section></div>
 {selectedRole&&!selected&&<section className="data-card" style={{marginTop:16}}><div className="data-card-head"><div><strong>صلاحيات الدور: {selectedRole.name_ar}</strong><span>{selectedRole.is_system?'الدور النظامي للعرض فقط':'يمكن تخصيص صلاحيات هذا الدور'}</span></div></div><div className="permission-list">{permissions.map(p=>{const on=rolePermissionSet.has(p.id);return <div className="permission-row" key={p.id}><div><b>{p.name_ar}</b><small>{p.code}</small></div><button className={on?'permission allow':'permission'} disabled={selectedRole.is_system||!roleManage||saving==='rp'+p.id} onClick={()=>void setRolePermission(p.id,!on)}>{on?<><Check size={15}/> مفعلة</>:<><Plus size={15}/> تفعيل</>}</button></div>})}</div></section>}
 </main>}
