import { useEffect,useMemo,useState } from 'react';
import { ShieldCheck,Users,UserPlus,KeyRound,Check,X,Plus,BriefcaseBusiness } from 'lucide-react';
import { supabase } from '../supabase';
import { getAccessState,can } from '../lib/rbac';

type Member=any;
export default function Team(){
 const[members,setMembers]=useState<Member[]>([]),[roles,setRoles]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[overrides,setOverrides]=useState<any[]>([]),[rolePerms,setRolePerms]=useState<any[]>([]),[access,setAccess]=useState<any>(null),[selected,setSelected]=useState<Member|null>(null),[selectedRole,setSelectedRole]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[showRoleForm,setShowRoleForm]=useState(false),[roleName,setRoleName]=useState(''),[roleNameEn,setRoleNameEn]=useState('');
 async function load(){setLoading(true);setError('');try{const a=await getAccessState();const{data:{user}}=await supabase.auth.getUser();setAccess({...a,userId:user?.id});if(!a.charityId){setLoading(false);return}const[m,p]=await Promise.all([supabase.from('charity_members').select('id,user_id,status,role_id,created_at,roles(code,name_ar,name_en,is_system,charity_id)').eq('charity_id',a.charityId).order('created_at'),supabase.from('permissions').select('id,code,name_ar,name_en').order('code')]);if(m.error)throw m.error;if(p.error)throw p.error;const{data:r,error:re}=await supabase.rpc('list_manageable_roles');if(re)throw re;setMembers(m.data||[]);setRoles(r||[]);setPermissions(p.data||[]);if(selected){const fresh=(m.data||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e:any){setError(e.message||'تعذر تحميل الفريق')}finally{setLoading(false)}}
 async function loadOverrides(member:Member){setSelected(member);setSelectedRole(roles.find(r=>r.id===member.role_id)||null);setError('');const{data,error:e}=await supabase.from('user_permission_overrides').select('permission_id,effect').eq('charity_member_id',member.id);if(e)setError(e.message);else setOverrides(data||[])}
 async function loadRolePermissions(role:any){setSelectedRole(role);const{data,error:e}=await supabase.from('role_permissions').select('permission_id').eq('role_id',role.id);if(e)setError(e.message);else setRolePerms(data||[])}
 useEffect(()=>{void load()},[]);
 async function changeRole(member:Member,roleId:string){if(!access?.charityId||!can(access,'team.manage')||member.user_id===access.userId)return;setSaving('role');const{error:e}=await supabase.rpc('change_member_role',{p_member_id:member.id,p_role_id:roleId});if(e)setError(e.message);else await load();setSaving('')}
 async function setPermission(permissionId:string,effect:'allow'|'deny'){if(!selected||!can(access||{permissions:[]},'team.manage')||selected.user_id===access?.userId)return;setSaving(permissionId+effect);const{error:e}=await supabase.rpc('set_member_permission',{p_member_id:selected.id,p_permission_id:permissionId,p_effect:effect});if(e)setError(e.message);else await loadOverrides(selected);setSaving('')}
 async function setRolePermission(permissionId:string,enabled:boolean){if(!selectedRole||!can(access||{permissions:[]},'roles.manage')||selectedRole.is_system)return;setSaving('rp'+permissionId);const{error:e}=await supabase.rpc('set_role_permission',{p_role_id:selectedRole.id,p_permission_id:permissionId,p_enabled:enabled});if(e)setError(e.message);else await loadRolePermissions(selectedRole);setSaving('')}
 async function createRole(){if(!can(access||{permissions:[]},'roles.manage')||!roleName.trim())return;setSaving('newrole');const{data,error:e}=await supabase.rpc('create_custom_role',{p_name_ar:roleName.trim(),p_name_en:roleNameEn.trim()||null});if(e)setError(e.message);else{setShowRoleForm(false);setRoleName('');setRoleNameEn('');await load();const r=(roles||[]).find(x=>x.id===data);if(r)await loadRolePermissions(r)}setSaving('')}
 const overrideMap=useMemo(()=>Object.fromEntries(overrides.map(x=>[x.permission_id,x.effect])),[overrides]);
 const rolePermissionSet=useMemo(()=>new Set(rolePerms.map(x=>x.permission_id)),[rolePerms]);
 if(loading)return <main className="module-page"><div className="loading">جاري تحميل فريق الجمعية...</div></main>;
 const manageable=can(access||{permissions:[]},'team.manage'),roleManage=can(access||{permissions:[]},'roles.manage');
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><Users size={15}/> الحوكمة والصلاحيات</span><h1>فريق الجمعية</h1><p>الأدوار والصلاحيات الفردية تحت تحكم مركزي وآمن.</p></div><div style={{display:'flex',gap:8}}><button className="ghost" disabled={!roleManage} onClick={()=>setShowRoleForm(true)}><BriefcaseBusiness size={17}/> دور مخصص</button><button className="primary" disabled={!manageable}><UserPlus size={18}/> دعوة موظف</button></div></div>{error&&<div className="error">{error}</div>}
 <div className="kpis"><div className="kpi"><div className="kpi-icon"><Users/></div><span>أعضاء الفريق</span><strong>{members.length}</strong></div><div className="kpi"><div className="kpi-icon"><KeyRound/></div><span>الصلاحيات المتاحة</span><strong>{permissions.length}</strong></div><div className="kpi"><div className="kpi-icon"><ShieldCheck/></div><span>الأدوار</span><strong>{roles.length}</strong></div></div>
 {showRoleForm&&<section className="data-card" style={{marginTop:16}}><div className="data-card-head"><strong>إنشاء دور مخصص</strong><button className="ghost" onClick={()=>setShowRoleForm(false)}>إغلاق</button></div><div className="form-grid"><label>اسم الدور بالعربية<input value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder="مثال: مسؤول المستفيدين"/></label><label>اسم الدور بالإنجليزية<input value={roleNameEn} onChange={e=>setRoleNameEn(e.target.value)} placeholder="Beneficiaries Officer"/></label></div><div style={{marginTop:12}}><button className="primary" disabled={saving==='newrole'||!roleName.trim()} onClick={()=>void createRole()}>{saving==='newrole'?'جاري الإنشاء...':'إنشاء الدور'}</button></div></section>}
 <div className="split-layout" style={{marginTop:16}}><section className="data-card"><div className="data-card-head"><strong>أعضاء الفريق</strong><span>اختر عضوًا لإدارة صلاحياته</span></div><div className="table-wrap"><table><thead><tr><th>العضو</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>{members.map(m=><tr key={m.id} className={selected?.id===m.id?'selected-row':''}><td><div className="person"><div className="person-avatar"><Users size={17}/></div><div><b>{m.user_id.slice(0,8)}…</b><small>معرّف عضو داخلي</small></div></div></td><td><select disabled={!manageable||m.user_id===access?.userId||saving==='role'} value={m.role_id||''} onChange={e=>void changeRole(m,e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.name_ar}</option>)}</select></td><td><span className={'status '+(m.status==='active'?'active':'inactive')}>{m.status==='active'?'نشط':'غير نشط'}</span></td><td><button className="ghost" onClick={()=>void loadOverrides(m)}>صلاحيات فردية</button></td></tr>)}</tbody></table></div></section>
 <section className="data-card"><div className="data-card-head"><div><strong>{selected?'صلاحيات العضو':'إدارة الأدوار'}</strong><span>{selected?'التعديل الفردي يتغلب على صلاحيات الدور':'اختر دورًا لمراجعة صلاحياته'}</span></div>{selected&&<span className="status active">{selected.roles?.name_ar||'عضو'}</span>}</div>{selected?<div className="permission-list">{permissions.map(p=>{const ov=overrideMap[p.id];return <div className="permission-row" key={p.id}><div><b>{p.name_ar}</b><small>{p.code}</small></div><div className="permission-actions"><button className={ov==='allow'?'permission allow':'permission'} disabled={!manageable||saving===p.id+'allow'} onClick={()=>void setPermission(p.id,'allow')}><Check size={15}/> سماح</button><button className={ov==='deny'?'permission deny':'permission'} disabled={!manageable||saving===p.id+'deny'} onClick={()=>void setPermission(p.id,'deny')}><X size={15}/> منع</button><span className="permission-state">{ov==='allow'?'مسموح فرديًا':ov==='deny'?'ممنوع فرديًا':'من الدور'}</span></div></div>})}</div>:<div className="permission-list">{roles.map(r=><div className="permission-row" key={r.id}><div><b>{r.name_ar}</b><small>{r.is_system?'دور نظامي':'دور مخصص للجمعية'}</small></div><div className="permission-actions"><button className="ghost" onClick={()=>void loadRolePermissions(r)}>صلاحيات الدور</button></div></div>)}</div>}</section></div>
 {selectedRole&&!selected&&<section className="data-card" style={{marginTop:16}}><div className="data-card-head"><div><strong>صلاحيات الدور: {selectedRole.name_ar}</strong><span>{selectedRole.is_system?'الدور النظامي للعرض فقط':'يمكن تخصيص صلاحيات هذا الدور'}</span></div></div><div className="permission-list">{permissions.map(p=>{const on=rolePermissionSet.has(p.id);return <div className="permission-row" key={p.id}><div><b>{p.name_ar}</b><small>{p.code}</small></div><button className={on?'permission allow':'permission'} disabled={selectedRole.is_system||!roleManage||saving==='rp'+p.id} onClick={()=>void setRolePermission(p.id,!on)}>{on?<><Check size={15}/> مفعلة</>:<><Plus size={15}/> تفعيل</>}</button></div>})}</div></section>}
 </main>}
