import { useEffect,useState } from 'react';
import { ShieldCheck,Users,UserPlus,KeyRound } from 'lucide-react';
import { supabase } from '../supabase';
import { getAccessState,can } from '../lib/rbac';

export default function Team(){
 const [members,setMembers]=useState<any[]>([]),[roles,setRoles]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[access,setAccess]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const a=await getAccessState();setAccess(a);if(!a.charityId){setLoading(false);return}const [m,r,p]=await Promise.all([supabase.from('charity_members').select('id,user_id,status,role_id,created_at,roles(code,name_ar)').eq('charity_id',a.charityId).order('created_at'),supabase.from('roles').select('id,code,name_ar,name_en,is_system').order('name_ar'),supabase.from('permissions').select('id,code,name_ar,name_en').order('code')]);if(m.error)throw m.error;if(r.error)throw r.error;if(p.error)throw p.error;setMembers(m.data||[]);setRoles(r.data||[]);setPermissions(p.data||[])}catch(e:any){setError(e.message||'تعذر تحميل الفريق')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function changeRole(member:any,roleId:string){if(!access?.charityId||!can(access,'team.manage')||member.user_id===access.userId)return;const {error:e}=await supabase.from('charity_members').update({role_id:roleId}).eq('id',member.id).eq('charity_id',access.charityId);if(e)setError(e.message);else await load()}
 if(loading)return <main className="module-page"><div className="loading">جاري تحميل فريق الجمعية...</div></main>;
 return <main className="module-page"><div className="module-head"><div><span className="eyebrow"><Users size={15}/> الحوكمة والصلاحيات</span><h1>فريق الجمعية</h1><p>إدارة الأعضاء والأدوار والصلاحيات من مكان واحد.</p></div><button className="primary" disabled={!can(access||{permissions:[]},'team.manage')}><UserPlus size={18}/> إضافة موظف</button></div>{error&&<div className="error">{error}</div>}<div className="kpis"><div className="kpi"><div className="kpi-icon"><Users/></div><span>أعضاء الفريق</span><strong>{members.length}</strong></div><div className="kpi"><div className="kpi-icon"><KeyRound/></div><span>الصلاحيات المتاحة</span><strong>{permissions.length}</strong></div><div className="kpi"><div className="kpi-icon"><ShieldCheck/></div><span>الدور الحالي</span><strong>{access?.roleCode||'—'}</strong></div></div><section className="data-card" style={{marginTop:16}}><div className="data-card-head"><strong>الأعضاء</strong><span>التعديل محكوم بصلاحية team.manage</span></div><div className="table-wrap"><table><thead><tr><th>العضو</th><th>الدور</th><th>الحالة</th><th>تاريخ الانضمام</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="person"><div className="person-avatar"><Users size={17}/></div><div><b>{m.user_id.slice(0,8)}…</b><small>معرّف عضو داخلي</small></div></div></td><td><select disabled={!can(access||{permissions:[]},'team.manage')||m.user_id===access?.userId} value={m.role_id||''} onChange={e=>void changeRole(m,e.target.value)}>{roles.map(r=><option key={r.id} value={r.id}>{r.name_ar}</option>)}</select></td><td><span className={'status '+(m.status==='active'?'active':'inactive')}>{m.status==='active'?'نشط':'غير نشط'}</span></td><td>{new Date(m.created_at).toLocaleDateString('ar-SA')}</td></tr>)}</tbody></table></div></section></main>}
