import { useEffect, useRef, useState } from 'react';
import { Plus, Trash2, X, CheckCircle2, FileText } from 'lucide-react';
import { supabase } from '../supabase';
import { friendlyError } from '../lib/requests';
import './accounting-workbench.css';

type Account = { id: string; code: string; name_ar: string; is_active: boolean };
type Dimension = { id: string; name_ar: string; is_active: boolean };
type Period = { id: string; name: string; status: string; starts_on: string; ends_on: string };
type Line = { key: string; account_id: string; debit: string; credit: string; amount: string; description: string; cost_center_id: string; fund_id: string };
type Props = { accounts: Account[]; dimensions: { cost_centers: Dimension[]; funds: Dimension[] }; periods: Period[]; onChanged: () => Promise<void>; canManage: boolean };
type Budget = { id: string; name: string; period_name: string; status: string; total_amount: number; lines: { id: string; account_code: string; account_name: string; amount: number; note?: string }[] };
type Actual = { line_id: string; account_code: string; name_ar: string; budget_amount: number; actual_amount: number; variance: number };
const freshLine = (): Line => ({ key: crypto.randomUUID(), account_id: '', debit: '', credit: '', amount: '', description: '', cost_center_id: '', fund_id: '' });
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
export const formatMoney = (n: number | string) => Number(n || 0).toLocaleString('ar-SA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const cents = (n: string) => Math.round(Number(n || 0) * 100);

function Dialog({ title, busy, close, children }: { title: string; busy: boolean; close: () => void; children: React.ReactNode }) {
 const ref = useRef<HTMLDialogElement>(null);
 useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
 return <dialog ref={ref} className="finance-dialog" onCancel={e => { e.preventDefault(); if (!busy) close(); }} aria-label={title}>
  <div className="finance-dialog-head"><div><span className="eyebrow">جمعيتي · المركز المالي</span><h2>{title}</h2></div><button type="button" className="secondary" aria-label="إغلاق" disabled={busy} onClick={close}><X /></button></div>{children}
 </dialog>;
}

function LineEditor({ lines, setLines, accounts, dimensions, budget = false, disabled }: { lines: Line[]; setLines: (lines: Line[]) => void; accounts: Account[]; dimensions: Props['dimensions']; budget?: boolean; disabled: boolean }) {
 const update = (key: string, field: keyof Line, value: string) => setLines(lines.map(l => l.key === key ? { ...l, [field]: value } : l));
 return <div className="finance-lines">{lines.map((line, i) => <fieldset key={line.key} disabled={disabled} className="finance-line"><legend>البند {(i + 1).toLocaleString('ar-SA')}</legend>
  <div className="finance-line-main"><label>الحساب<select required value={line.account_id} onChange={e => update(line.key,'account_id',e.target.value)}><option value="">اختر الحساب</option>{accounts.filter(a => a.is_active).map(a => <option key={a.id} value={a.id}>{a.code} — {a.name_ar}</option>)}</select></label>
   {budget ? <label>المبلغ المخطط (ر.س)<input inputMode="decimal" type="number" required min="0.01" step="0.01" value={line.amount} onChange={e => update(line.key,'amount',e.target.value)} /></label> : <><label>مدين (ر.س)<input aria-label={`مدين البند ${i+1}`} type="number" min="0" step="0.01" value={line.debit} onChange={e => update(line.key,'debit',e.target.value)} /></label><label>دائن (ر.س)<input aria-label={`دائن البند ${i+1}`} type="number" min="0" step="0.01" value={line.credit} onChange={e => update(line.key,'credit',e.target.value)} /></label></>}
   <button type="button" className="secondary" aria-label={`حذف البند ${i+1}`} disabled={lines.length <= (budget ? 1 : 2)} onClick={() => setLines(lines.filter(l => l.key !== line.key))}><Trash2 /></button></div>
  <div className="finance-line-details"><label>البيان<input maxLength={500} value={line.description} onChange={e => update(line.key,'description',e.target.value)} /></label><label>مركز التكلفة<select value={line.cost_center_id} onChange={e => update(line.key,'cost_center_id',e.target.value)}><option value="">بدون تخصيص</option>{dimensions.cost_centers.filter(d => d.is_active).map(d => <option key={d.id} value={d.id}>{d.name_ar}</option>)}</select></label><label>الصندوق<select value={line.fund_id} onChange={e => update(line.key,'fund_id',e.target.value)}><option value="">بدون تخصيص</option>{dimensions.funds.filter(d => d.is_active).map(d => <option key={d.id} value={d.id}>{d.name_ar}</option>)}</select></label></div>
 </fieldset>)}<button type="button" className="secondary" disabled={disabled || lines.length >= 100} onClick={() => setLines([...lines, freshLine()])}><Plus /> إضافة بند</button></div>;
}

export function JournalComposer(props: Props) {
 const [open,setOpen] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState('');
 const [date,setDate] = useState(today), [description,setDescription] = useState(''), [lines,setLines] = useState<Line[]>(() => [freshLine(),freshLine()]);
 const token = useRef(crypto.randomUUID());
 const debit = lines.reduce((s,l) => s+cents(l.debit),0), credit = lines.reduce((s,l) => s+cents(l.credit),0);
 const balanced = debit > 0 && debit === credit;
 const period = props.periods.find(p => p.status === 'open' && date >= p.starts_on && date <= p.ends_on);
 async function submit(e: React.FormEvent) {
  e.preventDefault(); if(busy)return; setError('');
  if(!balanced || lines.some(l => !l.account_id || !Number.isFinite(cents(l.debit)) || !Number.isFinite(cents(l.credit)) || cents(l.debit)<0 || cents(l.credit)<0 || (cents(l.debit)>0)===(cents(l.credit)>0))) { setError('أدخل مبلغًا في طرف واحد لكل بند، وتأكد من تساوي إجمالي المدين والدائن.'); return; }
  if(!period){setError('اختر تاريخًا داخل فترة مالية مفتوحة.');return;}
  setBusy(true);
  try { const r = await supabase.rpc('accounting_post_journal',{p_description:description.trim(),p_entry_date:date,p_reference_type:'manual_ui',p_reference_id:token.current,p_lines:lines.map(l => ({account_id:l.account_id,debit:cents(l.debit)/100,credit:cents(l.credit)/100,description:l.description.trim()||null,cost_center_id:l.cost_center_id||null,fund_id:l.fund_id||null}))});if(r.error)throw r.error;setOpen(false);setLines([freshLine(),freshLine()]);setDescription('');token.current=crypto.randomUUID();setNotice('تم ترحيل القيد بنجاح.');await props.onChanged(); }
  catch(e){setError(friendlyError(e));} finally{setBusy(false);}
 }
 return <><div className="finance-action-bar"><div><h2>القيود اليومية</h2><p>أدخل بنود القيد وراجع التوازن قبل الترحيل.</p></div>{props.canManage && <button className="primary" onClick={() => {setError('');setOpen(true);}}><Plus /> قيد جديد</button>}</div>{notice && <p className="finance-success" role="status"><CheckCircle2 />{notice}</p>}
 {open && <Dialog title="قيد يومية جديد" busy={busy} close={() => setOpen(false)}><form onSubmit={submit}><fieldset disabled={busy} className="finance-fields"><div className="form-grid"><label>تاريخ القيد<input type="date" required value={date} onChange={e => setDate(e.target.value)} /></label><label>البيان العام<input autoFocus required minLength={3} maxLength={1000} value={description} onChange={e => setDescription(e.target.value)} placeholder="مثال: إثبات مصروفات برنامج الدعم" /></label></div><p className={period?'muted':'error'}>{period?`الفترة: ${period.name}`:'التاريخ لا يقع داخل فترة مالية مفتوحة.'}</p>
 <LineEditor {...props} lines={lines} setLines={setLines} disabled={busy}/><div className={`finance-totals ${balanced?'balanced':''}`} aria-live="polite"><span>مدين <b>{formatMoney(debit/100)}</b></span><span>دائن <b>{formatMoney(credit/100)}</b></span><span>{balanced?'القيد متوازن':`الفرق: ${formatMoney((debit-credit)/100)}`}</span></div>
 {error && <div className="error" role="alert">{error}</div>}<p className="muted">بعد الترحيل، تتم معالجة التصحيح بقيد عكسي مع الاحتفاظ بالسجل الأصلي.</p><div className="finance-footer"><button type="button" className="secondary" onClick={() => setOpen(false)}>رجوع</button><button className="primary" disabled={!balanced||!period||busy}>{busy?'جاري الترحيل…':'اعتماد وترحيل القيد'}</button></div></fieldset></form></Dialog>}</>;
}

export function BudgetWorkbench(props: Props & { budgets: Budget[] }) {
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[period,setPeriod]=useState(''),[lines,setLines]=useState<Line[]>(() => [freshLine()]);
 const [selected,setSelected]=useState<Budget|null>(null),[actual,setActual]=useState<Actual[]>([]),[reportLoading,setReportLoading]=useState(false),[reportError,setReportError]=useState('');
 const reportRequest=useRef(0);
 useEffect(() => () => {reportRequest.current++;},[]);
 const total=lines.reduce((s,l)=>s+cents(l.amount),0);
 async function create(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('accounting_budget_create',{p_period_id:period,p_name:name.trim(),p_lines:lines.map(l=>({account_id:l.account_id,amount:cents(l.amount)/100,note:l.description.trim()||null,cost_center_id:l.cost_center_id||null,fund_id:l.fund_id||null}))});if(r.error)throw r.error;setOpen(false);setName('');setLines([freshLine()]);await props.onChanged();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 async function approve(b:Budget){if(busy||!confirm(`اعتماد الموازنة «${b.name}» بإجمالي ${formatMoney(b.total_amount)} ر.س؟`))return;setBusy(true);setError('');try{const r=await supabase.rpc('accounting_budget_approve',{p_budget_id:b.id});if(r.error)throw r.error;await props.onChanged();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 async function report(b:Budget){const request=++reportRequest.current;setSelected(b);setActual([]);setReportError('');setReportLoading(true);try{const r=await supabase.rpc('accounting_budget_vs_actual',{p_budget_id:b.id});if(r.error)throw r.error;if(request===reportRequest.current)setActual((r.data||[]) as Actual[]);}catch(e){if(request===reportRequest.current)setReportError(friendlyError(e));}finally{if(request===reportRequest.current)setReportLoading(false);}}
 return <section><div className="finance-action-bar"><div><h2>الموازنات ومتابعة الإنفاق</h2><p>خطط لكل حساب وصندوق ومركز تكلفة، ثم قارن بالحركة المالية الفعلية.</p></div>{props.canManage&&<button className="primary" onClick={()=>{setError('');setPeriod(props.periods.find(p=>p.status==='open')?.id||'');setOpen(true);}}><Plus/> موازنة جديدة</button>}</div>{error&&!open&&<div className="error" role="alert">{error}</div>}
 {!props.budgets.length?<div className="empty">لا توجد موازنات. ابدأ بخطة للفترة المالية المفتوحة.</div>:<div className="finance-budget-grid">{props.budgets.map(b=><article className="finance-budget-card" key={b.id}><div className="finance-action-bar"><span className="status-pill">{b.status==='approved'?'معتمدة':b.status==='draft'?'مسودة':b.status}</span><small>{b.period_name}</small></div><h3>{b.name}</h3><strong className="finance-budget-total">{formatMoney(b.total_amount)} <small>ر.س</small></strong><p>{b.lines.length.toLocaleString('ar-SA')} بنود</p><div className="finance-footer"><button className="secondary" onClick={()=>void report(b)}><FileText/> المخطط مقابل الفعلي</button>{b.status==='draft'&&props.canManage&&<button className="primary" disabled={busy} onClick={()=>void approve(b)}>اعتماد</button>}</div></article>)}</div>}
 {open&&<Dialog title="إعداد موازنة مالية" busy={busy} close={()=>setOpen(false)}><form onSubmit={create}><fieldset disabled={busy} className="finance-fields"><div className="form-grid"><label>اسم الموازنة<input autoFocus required minLength={3} maxLength={200} value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: موازنة برامج الجمعية"/></label><label>الفترة المالية<select required value={period} onChange={e=>setPeriod(e.target.value)}><option value="">اختر فترة مفتوحة</option>{props.periods.filter(p=>p.status==='open').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><LineEditor {...props} budget lines={lines} setLines={setLines} disabled={busy}/><div className="finance-totals"><span>إجمالي الموازنة</span><b>{formatMoney(total/100)} ر.س</b></div>{error&&<div className="error" role="alert">{error}</div>}<div className="finance-footer"><button type="button" className="secondary" onClick={()=>setOpen(false)}>رجوع</button><button className="primary" disabled={busy||total<=0}>{busy?'جاري الحفظ…':'حفظ الموازنة كمسودة'}</button></div></fieldset></form></Dialog>}
 {selected&&<Dialog title={`المخطط مقابل الفعلي · ${selected.name}`} busy={false} close={()=>{reportRequest.current++;setSelected(null);}}><p>{selected.period_name} · الفعلي من القيود المرحّلة داخل الفترة.</p>{reportLoading?<p role="status">جاري إعداد المقارنة…</p>:reportError?<div className="error" role="alert">{reportError}<button className="secondary" onClick={()=>void report(selected)}>إعادة المحاولة</button></div>:<div className="table-wrap"><table><thead><tr><th>الحساب</th><th>المخطط</th><th>الفعلي</th><th>المخطط − الفعلي</th></tr></thead><tbody>{actual.map(l=><tr key={l.line_id}><td>{l.account_code} — {l.name_ar}</td><td>{formatMoney(l.budget_amount)}</td><td>{formatMoney(l.actual_amount)}</td><td>{formatMoney(l.variance)}</td></tr>)}</tbody></table><p className="muted">يعرض كل بند نطاقه المحدد؛ البنود ذات الأبعاد المتداخلة قد تتشارك بعض الحركات، لذلك لا نجمع الفعلي بينها.</p></div>}</Dialog>}
 </section>;
}

const accountTypes:Record<string,string>={asset:'أصول',liability:'التزامات',equity:'صافي الأصول',revenue:'إيرادات',expense:'مصروفات'};
export function AccountWorkbench({accounts,canManage,onChanged}:{accounts:(Account & {account_type:string})[];canManage:boolean;onChanged:()=>Promise<void>}){
 const [form,setForm]=useState<{id:string;code:string;name_ar:string;account_type:string;is_active:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();if(!form||busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('accounting_save_account',{p_account_id:form.id||null,p_code:form.code.trim(),p_name_ar:form.name_ar.trim(),p_account_type:form.account_type,p_is_active:form.is_active});if(r.error)throw r.error;setForm(null);await onChanged();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 const filtered=accounts.filter(a=>`${a.code} ${a.name_ar}`.toLowerCase().includes(search.toLowerCase()));
 return <section><div className="finance-action-bar"><div><h2>دليل الحسابات</h2><p>حسابات الجمعية وتصنيفها المحاسبي.</p></div>{canManage&&<button className="primary" onClick={()=>{setError('');setForm({id:'',code:'',name_ar:'',account_type:'expense',is_active:true});}}><Plus/> حساب جديد</button>}</div><label className="search-box">بحث في الحسابات<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="الاسم أو الكود"/></label><div className="table-wrap"><table><thead><tr><th>الكود</th><th>الحساب</th><th>النوع</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td>{a.code}</td><td>{a.name_ar}</td><td>{accountTypes[a.account_type]||a.account_type}</td><td>{a.is_active?'نشط':'موقوف'}</td><td>{canManage&&<button className="secondary" onClick={()=>{setError('');setForm({...a});}}>تعديل</button>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">لا توجد حسابات مطابقة.</div>}</div>
 {form&&<Dialog title={form.id?'تعديل الحساب':'إضافة حساب'} busy={busy} close={()=>setForm(null)}><form onSubmit={save}><fieldset disabled={busy} className="finance-fields"><div className="form-grid"><label>كود الحساب<input autoFocus={!form.id} required pattern="[A-Za-z0-9._\\-]{2,20}" disabled={!!form.id} value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>الاسم بالعربية<input autoFocus={!!form.id} required maxLength={200} value={form.name_ar} onChange={e=>setForm({...form,name_ar:e.target.value})}/></label><label>التصنيف<select disabled={!!form.id} value={form.account_type} onChange={e=>setForm({...form,account_type:e.target.value})}>{Object.entries(accountTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>الحالة<select value={form.is_active?'active':'inactive'} onChange={e=>setForm({...form,is_active:e.target.value==='active'})}><option value="active">نشط</option><option value="inactive">موقوف عن الاختيار في قيود جديدة</option></select></label></div>{form.id&&<p className="muted">يبقى الكود والتصنيف ثابتين للحفاظ على اتساق السجل المحاسبي.</p>}{error&&<div className="error" role="alert">{error}</div>}<div className="finance-footer"><button type="button" className="secondary" onClick={()=>setForm(null)}>رجوع</button><button className="primary" disabled={busy}>{busy?'جاري الحفظ…':'حفظ الحساب'}</button></div></fieldset></form></Dialog>}</section>;
}
