import {useEffect,useRef,useState} from 'react';
import {Sparkles,ClipboardCheck} from 'lucide-react';
import {supabase} from '../supabase';
import {getAccessState} from '../lib/rbac';
import './beneficiary-analysis.css';
const labels:Record<string,string>={monthly_income:'دخل الأسرة',monthly_rent:'الإيجار',household_size:'أفراد المنزل',dependents:'المعالون'};
export default function BeneficiaryAnalysis({applicationId,beneficiaryId}:{applicationId?:string;beneficiaryId?:string}){
 const [allowed,setAllowed]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('');const controller=useRef<AbortController|null>(null);
 useEffect(()=>{let live=true;setResult(null);setError('');setBusy(false);setAllowed(false);getAccessState().then(a=>{if(live)setAllowed(a.workspaceEnabled&&a.permissions.includes('beneficiaries.manage'))}).catch(()=>{});return()=>{live=false;controller.current?.abort();controller.current=null}},[applicationId,beneficiaryId]);
 async function analyze(){const current=new AbortController();controller.current=current;setBusy(true);setError('');setResult(null);const timer=setTimeout(()=>current.abort(),45000);try{const {data,error:sessionError}=await supabase.auth.getSession();if(sessionError||!data.session)throw new Error('سجل الدخول مجددًا.');const r=await fetch('/api/beneficiary-analysis',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(applicationId?{applicationId}:{beneficiaryId}),signal:current.signal});const payload=await r.json();if(!r.ok)throw new Error(payload.error||'تعذر التحليل');if(!current.signal.aborted)setResult(payload)}catch(e:any){if(controller.current===current)setError(e.name==='AbortError'?'انتهت مهلة التحليل؛ يمكنك إعادة المحاولة.':e.message||'تعذر التحليل')}finally{clearTimeout(timer);if(controller.current===current)setBusy(false)}}
 if(!allowed)return null;
 function rows(items:any[]){return <ul>{items.map((x,i)=><li key={i}><p>{x.text}</p><small>المصدر: {x.sources.map((s:string)=>labels[s]||s).join(' + ')}</small></li>)}</ul>}
 return <section className="beneficiary-analysis"><div className="analysis-heading"><div><span><Sparkles size={18}/> مساعد الباحث الاجتماعي</span><h3>اقرأ الحالة بوضوح أكبر</h3></div><ClipboardCheck size={28}/></div><p>مراجعة الأرقام والنواقص وأسئلة الاستيضاح. عند تفعيل التحليل اللغوي، تُرسل المؤشرات الرقمية فقط إلى خدمة الذكاء الاصطناعي.</p><button className="primary" disabled={busy} onClick={analyze}>{busy?'جاري مراجعة الملف…':result?'إعادة التحليل من أحدث البيانات':'تحليل الملف'}</button>{busy&&<p role="status">تجهيز ملخص الحالة…</p>}{error&&<p className="error" role="alert">{error}</p>}{result&&<div className="analysis-results"><span className="analysis-mode">{result.mode==='ai'?'ملخص لغوي بالذكاء الاصطناعي + حسابات موثقة':'مراجعة حسابية — ليست تحليلًا بالذكاء الاصطناعي'}</span>{result.notice&&<p role="status">{result.notice}</p>}<h4>حقائق من إفادة الأسرة</h4>{rows(result.facts)}{result.missing.length>0&&<><h4>بيانات تحتاج استكمالًا</h4><p>{result.missing.join('، ')}</p></>}<h4>نقاط للمراجعة</h4>{rows(result.questions)}{result.review&&<><h4>مسودة ملخص للباحث</h4><p>{result.review.summary}</p><h4>أسئلة مقترحة بالذكاء الاصطناعي</h4>{rows(result.review.questions)}<h4>حدود التحليل</h4><ul>{result.review.limitations.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>}<p className="analysis-disclaimer">إفادة الأسرة لم تُتحقق تلقائيًا، ولم تُفحص المستندات. راجع المخرجات؛ لا تحدد هذه المراجعة الاستحقاق أو ترتيب الأولوية ولا تغيّر حالة الطلب.</p><small>أُنشئ: {new Date(result.generated_at).toLocaleString('ar-SA')} · حدّث التحليل بعد أي تعديل للملف.</small><details><summary>بيانات التتبع</summary><p dir="ltr">{result.id}<br/>{result.model||result.version}</p></details></div>}</section>
}
