import { useEffect,useRef,useState } from 'react';
import { Download,FileText,Trash2,UploadCloud } from 'lucide-react';
import { supabase } from '../supabase';
import { getAccessState } from '../lib/rbac';

const allowed=['application/pdf','image/jpeg','image/png','image/webp'];
export default function BeneficiaryDocuments({beneficiaryId}:{beneficiaryId:string}){
 const input=useRef<HTMLInputElement>(null);const[rows,setRows]=useState<any[]>([]),[drag,setDrag]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const r=await supabase.from('beneficiary_documents').select('id,bucket_id,object_path,document_type,original_name,mime_type,size_bytes,source,created_at').eq('beneficiary_id',beneficiaryId).order('created_at',{ascending:false});if(r.error)setError(r.error.message);else setRows(r.data||[])}useEffect(()=>{void load()},[beneficiaryId]);
 async function upload(file?:File){if(!file)return;if(file.size>10*1024*1024)return setError('الحد الأقصى 10MB.');if(!allowed.includes(file.type))return setError('يُسمح بملفات PDF وJPG وPNG وWEBP فقط.');setBusy(true);setError('');const access=await getAccessState();if(!access.charityId){setBusy(false);return setError('لا توجد جمعية فعالة.')}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${access.charityId}/${beneficiaryId}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('beneficiary-documents').upload(path,file,{contentType:file.type,upsert:false});if(up.error){setBusy(false);return setError(up.error.message)}const meta=await supabase.rpc('register_beneficiary_document',{p_beneficiary_id:beneficiaryId,p_object_path:path,p_document_type:file.type==='application/pdf'?'document':'image',p_original_name:file.name,p_mime_type:file.type,p_size_bytes:file.size});if(meta.error){await supabase.storage.from('beneficiary-documents').remove([path]);setError(meta.error.message)}else await load();setBusy(false)}
 async function download(row:any){const r=await supabase.storage.from(row.bucket_id||'beneficiary-documents').createSignedUrl(row.object_path,60);if(r.error)setError(r.error.message);else window.open(r.data.signedUrl,'_blank','noopener,noreferrer')}
 async function remove(row:any){if(!confirm('هل تريد حذف المستند نهائيًا؟'))return;setBusy(true);const rpc=await supabase.rpc('remove_beneficiary_document',{p_document_id:row.id});if(rpc.error)setError(rpc.error.message);else{await supabase.storage.from(row.bucket_id||'beneficiary-documents').remove([row.object_path]);await load()}setBusy(false)}
 return <section className="panel beneficiary-documents"><div className="panel-title"><div><span>ملفات محمية</span><h2>مستندات المستفيد</h2></div><FileText/></div><div className={'document-drop '+(drag?'drag':'')}onDragOver={e=>{e.preventDefault();setDrag(true)}}onDragLeave={()=>setDrag(false)}onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files[0])}}onClick={()=>input.current?.click()}><UploadCloud/><b>{busy?'جاري الرفع...':'اسحب الملف هنا أو اضغط للاختيار'}</b><span>PDF / JPG / PNG / WEBP — حتى 10MB</span><input ref={input}type="file"hidden accept=".pdf,.jpg,.jpeg,.png,.webp"onChange={e=>upload(e.target.files?.[0])}/></div>{error&&<div className="error">{error}</div>}<div className="document-list">{rows.map(row=><div key={row.id}><span className="document-icon"><FileText/></span><div><b>{row.original_name}</b><small>{(Number(row.size_bytes||0)/1024).toLocaleString('ar-SA',{maximumFractionDigits:0})} KB · {new Date(row.created_at).toLocaleDateString('ar-SA')}</small></div><button className="icon"onClick={()=>download(row)}title="عرض أو تنزيل"><Download/></button><button className="icon danger-icon"disabled={busy}onClick={()=>remove(row)}title="حذف"><Trash2/></button></div>)}</div></section>
}
