import {useEffect,useState} from 'react';
import {supabase} from '../supabase';

const options:Record<string,Record<string,string>>={marital_status:{single:'أعزب / عزباء',married:'متزوج / متزوجة',divorced:'مطلق / مطلقة',widowed:'أرمل / أرملة'},housing:{owned:'ملك',rented:'إيجار',hosted:'لدى الأسرة / مستضاف',temporary:'سكن مؤقت'},employment:{employed:'موظف',unemployed:'بلا عمل',retired:'متقاعد',self_employed:'عمل حر',unable:'غير قادر على العمل'}};
const labels:Record<string,string>={monthly_income:'إجمالي دخل الأسرة الشهري (ر.س)',monthly_rent:'الإيجار الشهري (ر.س)',household_size:'عدد المقيمين في المنزل شاملًا مقدم الطلب',dependents:'عدد المعالين',marital_status:'الحالة الاجتماعية',housing:'نوع السكن',employment:'الحالة الوظيفية',needs_description:'وصف الاحتياج ومصادر الدخل'};
const initial={monthly_income:'',monthly_rent:'0',household_size:'',dependents:'',marital_status:'single',housing:'owned',employment:'unemployed',needs_description:''};
export default function HouseholdProfile({applicationId,beneficiaryId,editable=false}:{applicationId?:string;beneficiaryId?:string;editable?:boolean}){
 const [data,setData]=useState<any>(null),[form,setForm]=useState(initial),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[declaration,setDeclaration]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;setLoading(true);setError('');supabase.rpc('beneficiary_household',{p_application_id:applicationId||null,p_beneficiary_id:beneficiaryId||null}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setData(r.data);if(r.data?.profile)setForm({...initial,...r.data.profile})}setLoading(false)});return()=>{live=false}},[applicationId,beneficiaryId]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved('');try{const r=await supabase.rpc('save_my_beneficiary_household',{p_income:Number(form.monthly_income),p_rent:form.housing==='rented'?Number(form.monthly_rent):0,p_size:Number(form.household_size),p_dependents:Number(form.dependents),p_marital:form.marital_status,p_housing:form.housing,p_employment:form.employment,p_needs:form.needs_description,p_declaration:declaration});if(r.error)throw r.error;setSaved('تم حفظ البيانات. تحتاج الجمعية مراجعة الشواهد بعد آخر تعديل.');setDeclaration(false)}catch(e:any){setError(e.message||'تعذر الحفظ')}finally{setBusy(false)}}
 const canEdit=editable&&data?.application_id&&data?.status!=='approved';
 return <section className="panel" style={{marginBlock:20}}><h2>الملف الاجتماعي والاقتصادي</h2>{loading?<p>جاري تحميل البيانات…</p>:canEdit?<form onSubmit={save}><p>أدخل معلومات الأسرة الفعلية. تظهر هذه البيانات للجمعية التي قدمت لها فقط.</p><div className="form-grid">{Object.keys(options).map(key=><label key={key}>{labels[key]}<select value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}>{Object.entries(options[key]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}{['monthly_income','household_size','dependents',...(form.housing==='rented'?['monthly_rent']:[])].map(key=><label key={key}>{labels[key]}<input required type="number" min={key==='household_size'?1:0} max={key==='household_size'?100:key==='dependents'?Math.max(0,Number(form.household_size)-1):10000000} step={key.includes('monthly')?'0.01':'1'} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label>{labels.needs_description}<textarea required minLength={10} maxLength={3000} rows={4} value={form.needs_description} onChange={e=>setForm({...form,needs_description:e.target.value})}/></label><label style={{display:'flex',alignItems:'center'}}><input type="checkbox" required checked={declaration} onChange={e=>setDeclaration(e.target.checked)}/>أقر بصحة البيانات وأوافق على مراجعتها وشواهدها لدى الجمعية.</label><button className="primary" disabled={busy}>{busy?'جاري الحفظ…':'حفظ بيانات الأسرة'}</button></form>:data?.profile?<><div className="detail-list">{Object.entries(labels).map(([key,label])=><div key={key}><span>{label}</span><strong style={{whiteSpace:'pre-wrap',maxWidth:'65%'}}>{options[key]?.[data.profile[key]]??String(data.profile[key]??'—')}</strong></div>)}</div><div className="privacy-note"><div><b>مؤشرات احتياج لمساندة الباحث الاجتماعي</b><p>دخل الفرد: {data.income_per_person} ر.س شهريًا · المتبقي للأسرة بعد الإيجار: {data.remaining_after_rent} ر.س</p><p>محسوبة من إفادة المستفيد؛ لا تثبت الاستحقاق ولا تتحقق من صحة المستندات. القرار للباحث والجمعية بعد مراجعة الشواهد.</p></div></div></>:<p>لم يُكمل المستفيد بيانات الأسرة بعد.</p>}{error&&<div className="error" role="alert">{error}</div>}{saved&&<div className="success" role="status">{saved}</div>}</section>;
}
