import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
const empty={mission:'',vision:'',programs:'',contact_email:'',contact_phone:'',address:'',bank_name:'',bank_holder:'',iban:'',published:false};
export default function PublicSiteEditor(){
 const [site,setSite]=useState(empty),[id,setId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true;supabase.rpc('manage_charity_public_site').then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setSite({...empty,...r.data?.site});setId(r.data?.charity_id||'')}});return()=>{live=false}},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await supabase.rpc('manage_charity_public_site',{p_data:site});if(r.error)throw r.error;setMessage('تم حفظ الصفحة وإعدادات ظهورها.')}catch(e:any){setError(e.message||'تعذر الحفظ')}finally{setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('تم نسخ الرابط.')}catch{setError('تعذر النسخ التلقائي؛ يمكنك نسخ الرابط من الحقل.')}}
 return <section className="panel" style={{marginTop:24}}><h2>موقع الجمعية والتسويق للمستفيدين</h2><p>شارك رابط الموقع للتعريف بخدماتكم، أو رابط الانضمام المباشر لاستقبال المستفيدين.</p>{id&&<div className="form-grid">{[['الموقع العام',`/charity/${id}`],['رابط انضمام المستفيدين',`/beneficiary-apply?charity=${id}`]].map(([label,path])=><label key={path}>{label}<input readOnly dir="ltr" value={location.origin+path}/><button type="button" className="secondary" onClick={()=>copy(location.origin+path)}>نسخ الرابط</button></label>)}</div>}<form onSubmit={save}><div className="form-grid">{[['mission','رسالتنا'],['vision','رؤيتنا'],['programs','البرامج والخدمات — برنامج في كل سطر']].map(([key,label])=><label key={key}>{label}<textarea maxLength={3000} rows={4} value={String(site[key as keyof typeof site])} onChange={e=>setSite({...site,[key]:e.target.value})}/></label>)}</div><div className="form-grid">{[['contact_email','البريد العام'],['contact_phone','هاتف التواصل'],['address','العنوان'],['bank_name','اسم البنك'],['bank_holder','اسم صاحب الحساب القانوني'],['iban','الآيبان السعودي']].map(([key,label])=><label key={key}>{label}<input maxLength={250} type={key==='contact_email'?'email':'text'} dir={key==='iban'?'ltr':undefined} value={String(site[key as keyof typeof site])} onChange={e=>setSite({...site,[key]:e.target.value})}/></label>)}</div><p>التحويل البنكي فقط. تحقق من ملكية الحساب للجمعية قبل نشره؛ صحة صيغة الآيبان لا تثبت ملكيته. لا يعتبر التحويل مستلمًا محاسبيًا حتى يراجعه الفريق المالي.</p><label style={{display:'flex',alignItems:'center'}}><input type="checkbox" checked={site.published} onChange={e=>setSite({...site,published:e.target.checked})}/>نشر الموقع العام — يتطلب اعتماد الجمعية واشتراكًا فعالًا</label>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="primary" disabled={busy||!id}>{busy?'جاري الحفظ…':'حفظ موقع الجمعية'}</button></form></section>;
}
