import {useEffect,useRef,useState} from 'react';
import {UploadCloud,ImagePlus} from 'lucide-react';
import {supabase} from '../supabase';
import {getAccessState} from '../lib/rbac';
import {friendlyError} from '../lib/requests';
import {safeHttps} from '../lib/publicSite';
export default function PublicImageUpload({value,onChange,kind='content',disabled=false,onBusyChange}:{value:string;onChange:(url:string)=>void;kind?:'logo'|'content';disabled?:boolean;onBusyChange?:(busy:boolean)=>void}){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function choose(f?:File){setError('');setMessage('');if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024||!f.size){setError('اختر صورة JPG أو PNG أو WEBP بحجم لا يتجاوز ٥ ميجابايت.');return}setFile(f)}
 async function upload(){if(!file)return;setBusy(true);onBusyChange?.(true);setError('');try{const access=await getAccessState(true);const charity=access.workspaceCharityId||access.charityId;if(!charity||!access.permissions.includes('onboarding.manage'))throw new Error('لا توجد صلاحية لتعديل صور الجمعية.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw new Error('أبعاد الصورة كبيرة جدًا. اختر نسخة أصغر.')}const ratio=Math.min(1,(kind==='logo'?800:1800)/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const ctx=canvas.getContext('2d');if(!ctx){bitmap.close();throw new Error('تعذر تجهيز الصورة.')}ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('تعذر تجهيز الصورة.')),'image/webp',.88));if(blob.size>5242880)throw new Error('الصورة كبيرة جدًا بعد التجهيز.');const path=`${charity}/${kind}/${crypto.randomUUID()}.webp`;const r=await supabase.storage.from('charity-public-media').upload(path,blob,{contentType:'image/webp',upsert:false,cacheControl:'31536000'});if(r.error)throw r.error;onChange(supabase.storage.from('charity-public-media').getPublicUrl(path).data.publicUrl);setFile(null);setMessage('تم رفع الصورة. اضغط حفظ في النموذج لاعتمادها.')}catch(e){setError(friendlyError(e))}finally{setBusy(false);onBusyChange?.(false)}}
 return <div className={`public-image-upload ${kind==='logo'?'logo-upload':''}`}><div className="media-preview">{preview||safeHttps(value)?<img src={preview||safeHttps(value)} alt={kind==='logo'?'معاينة شعار الجمعية':'معاينة صورة المحتوى'}/>:<ImagePlus size={36}/>}</div><div className="media-controls" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&!disabled)choose(e.dataTransfer.files[0])}}><strong>{kind==='logo'?'شعار يعبّر عن جمعيتك':'صورة تحكي أثر المبادرة'}</strong><p>اسحب الصورة هنا أو اخترها من جهازك. JPG / PNG / WEBP · حتى ٥ ميجابايت.</p><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden disabled={busy||disabled} onChange={e=>{choose(e.target.files?.[0]);e.target.value=''}}/><div className="account-links"><button type="button" className="secondary" disabled={busy||disabled} onClick={()=>input.current?.click()}><ImagePlus size={17}/> اختيار صورة</button>{file&&<button type="button" className="primary" disabled={busy||disabled} onClick={upload}><UploadCloud size={17}/>{busy?'جاري تجهيز الصورة ورفعها…':'رفع الصورة'}</button>}</div><small>هذه صور عامة للزوار؛ لا ترفع مستندات أو بيانات مستفيدين.</small>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}</div></div>
}
