import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {friendlyError} from '../lib/requests';
const kinds:Record<string,string>={board:'مجلس الإدارة والقيادة',campaign:'فرص التبرع',impact:'الإنجازات والأثر',disclosure:'الحوكمة والإفصاح'};
const empty={id:'',kind:'campaign',title:'',body:'',image_url:'',link_url:'',donation_type:'cash',target_amount:'',published:false};
export default function PublicContentEditor(){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState(empty),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await supabase.rpc('manage_public_content');if(r.error)throw r.error;setRows(r.data||[])}catch(e){setError(friendlyError(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await supabase.rpc('manage_public_content',{p_data:{...form,donation_type:form.kind==='campaign'?form.donation_type:null,target_amount:form.kind==='campaign'?form.target_amount:null}});if(r.error)throw r.error;setRows(r.data||[]);setForm(empty);setMessage('تم حفظ المحتوى. العناصر المنشورة تظهر على موقع الجمعية عند تفعيل نشر الموقع.')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 return <section className="panel"><h2>إدارة محتوى موقع الجمعية</h2><p>أنشئ فرص تبرع نقدية أو عينية، وعرّف بالمجلس، وانشر الإنجازات والإفصاحات. بيانات الموظفين والمتبرعين لا تُنشر تلقائيًا.</p><Link className="secondary" to="/updates">إدارة الأخبار وآخر التطورات</Link>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<div className="account-grid"><form onSubmit={save}><h3>{form.id?'تعديل المحتوى':'محتوى جديد'}</h3><label>القسم<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>{form.kind==='board'?'الاسم والصفة':'العنوان'}<input required minLength={2} maxLength={180} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>التفاصيل<textarea maxLength={6000} rows={5} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>رابط صورة عام وآمن<input type="url" pattern="https://.*" value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})}/></label>{form.kind==='disclosure'&&<label>رابط الوثيقة العامة<input type="url" pattern="https://.*" value={form.link_url||''} onChange={e=>setForm({...form,link_url:e.target.value})}/></label>}{form.kind==='campaign'&&<><label>نوع التبرع<select value={form.donation_type} onChange={e=>setForm({...form,donation_type:e.target.value})}><option value="cash">نقدي — تحويل بنكي</option><option value="in_kind">عيني — تواصل لتنسيق التسليم</option></select></label>{form.donation_type==='cash'&&<label>المبلغ المستهدف (اختياري، ر.س)<input type="number" min="0.01" step="0.01" value={form.target_amount||''} onChange={e=>setForm({...form,target_amount:e.target.value})}/></label>}</>}<label style={{display:'flex',alignItems:'center'}}><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>نشر هذا المحتوى — تأكد من دقته وحق الجمعية في نشره</label><div className="account-links"><button className="primary" disabled={busy}>{busy?'جاري الحفظ…':'حفظ المحتوى'}</button><button type="button" className="secondary" onClick={()=>setForm(empty)}>محتوى جديد</button></div></form><div><h3>المحتوى الحالي</h3>{loading?<p role="status">جاري التحميل…</p>:rows.length?rows.map(r=><article className="panel" key={r.id}><small>{kinds[r.kind]} · {r.published?'منشور':'مسودة'}</small><h4>{r.title}</h4><button className="secondary" onClick={()=>{setForm({...empty,...r,target_amount:r.target_amount||''});setMessage('')}}>تعديل / إيقاف النشر</button></article>):<p>ابدأ بإضافة أول محتوى لموقع الجمعية.</p>}</div></div></section>;
}
